Repository deegree/deegree3, pull requests merged in 2018-07, with the labels that each got.

#718 Fixed exception of WFS if requested feature (by resourceid) does not match the requested feature type (by typenames)
  deegree-datastores/deegree-featurestores/deegree-featurestore-sql/src/main/java/org/deegree/feature/persistence/sql/SQLFeatureStore.java
  deegree-datastores/deegree-featurestores/deegree-featurestore-sql/src/main/java/org/deegree/feature/persistence/sql/blob/FeatureBuilderBlob.java
Labels: bug, in progress, under review

#776 Fixed creation of gml time properties
  deegree-datastores/deegree-featurestores/deegree-featurestore-sql/src/main/java/org/deegree/feature/persistence/sql/rules/FeatureBuilderRelational.java
Labels: bug, in progress

#790 Fixed broken characters caused by the deegree console
  deegree-client/deegree-jsf-core/src/main/java/org/deegree/client/core/filter/InputFileFilter.java
Labels: bug, ready

#829 Move service file to correct project
  deegree-core/deegree-core-sqldialect/deegree-sqldialect-postgis/src/main/resources/META-INF/services/org.deegree.sqldialect.SQLDialectProvider
Labels: bug, under review

#835 Enhanced WMS configuration by the possibilitiy to configure supported request
  deegree-services/deegree-services-commons/src/main/java/org/deegree/services/encoding/LimitedSupportedEncodings.java
  deegree-services/deegree-services-commons/src/main/java/org/deegree/services/encoding/SupportedEncodings.java
  deegree-services/deegree-services-commons/src/main/java/org/deegree/services/encoding/UnlimitedSupportedEncodings.java
  deegree-services/deegree-services-commons/src/test/java/org/deegree/services/encoding/LimitedSupportedEncodingsTest.java
  deegree-services/deegree-services-wfs/src/main/java/org/deegree/services/wfs/GetCapabilitiesHandler.java
  deegree-services/deegree-services-wfs/src/main/java/org/deegree/services/wfs/WebFeatureService.java
  deegree-services/deegree-services-wfs/src/test/java/org/deegree/services/wfs/WebFeatureServiceTest.java
  deegree-services/deegree-services-wms/src/main/java/org/deegree/services/wms/controller/WMSController.java
  deegree-services/deegree-services-wms/src/main/java/org/deegree/services/wms/controller/capabilities/Capabilities130XMLAdapter.java
  deegree-services/deegree-services-wms/src/main/java/org/deegree/services/wms/controller/capabilities/Wms130SoapExtendedCapabilitesWriter.java
  deegree-services/deegree-services-wms/src/main/java/org/deegree/services/wms/controller/capabilities/WmsCapabilities111MetadataWriter.java
  deegree-services/deegree-services-wms/src/main/java/org/deegree/services/wms/controller/capabilities/WmsCapabilities130MetadataWriter.java
  deegree-services/deegree-services-wms/src/main/java/org/deegree/services/wms/utils/SupportedEncodingsParser.java
  deegree-services/deegree-services-wms/src/main/resources/META-INF/schemas/services/wms/3.4.0/example_complex.xml
  deegree-services/deegree-services-wms/src/main/resources/META-INF/schemas/services/wms/3.4.0/wms_configuration.xsd
  deegree-services/deegree-services-wms/src/test/java/org/deegree/services/wms/controller/capabilities/Wms130SoapExtendedCapabilitesWriterTest.java
  deegree-services/deegree-services-wms/src/test/java/org/deegree/services/wms/utils/SupportedEncodingsParserTest.java
  deegree-services/deegree-webservices-handbook/src/main/sphinx/webservices.rst
  deegree-services/deegree-webservices-handbook/src/main/sphinx/xml/deactivateSoap.xml
Labels: bug, in progress

#872 Fixed unexpected GetMap responses from remote WMS
  deegree-layers/deegree-layers-remotewms/src/main/java/org/deegree/layer/persistence/remotewms/RemoteWMSLayer.java
Labels: WMS, bug

#878 Fixed parsing of multiple type names from GET GetFeature request if filter is null
  deegree-core/deegree-core-protocol/deegree-protocol-wfs/src/main/java/org/deegree/protocol/wfs/query/kvp/QueryKVPAdapter.java
Labels: bug

#909 Updated deegree web services handbook chapter 2. Installation
  deegree-services/deegree-webservices-handbook/src/main/sphinx/installation.rst
Labels: enhancement
