Repository deegree/deegree3, pull requests merged in 2018-11, with the labels that each got.

#932 Upgraded PostgreSQL JDBC Driver to 42.2.5
  deegree-core/deegree-core-geometry/pom.xml
  deegree-core/deegree-core-sqldialect/deegree-sqldialect-postgis/pom.xml
  deegree-services/deegree-webservices-handbook/src/main/sphinx/serverconnections.rst
  pom.xml
Labels: enhancement, ready

#778 Improves the rendering of labels in polygons
  deegree-core/deegree-core-rendering-2d/src/main/java/org/deegree/rendering/r2d/GeometryClipper.java
  deegree-core/deegree-core-rendering-2d/src/main/java/org/deegree/rendering/r2d/Java2DLabelRenderer.java
Labels: enhancement, ready

#936 Fixed CITE WMS 1.1.1 URL
  deegree-workspaces/deegree-workspace-compliance-tests/src/main/workspace/datasources/remoteows/deegree-cite.xml
Labels: bug

#937 Changed maven build to produce no output
  .travis.yml
Labels: enhancement
