Repository deegree/deegree3, pull requests merged in 2018-03, with the labels that each got.

#741 Support Java SE 8 added
  .travis.yml
  deegree-core/deegree-core-commons/pom.xml
  deegree-core/deegree-core-workspace/src/main/java/org/deegree/workspace/standard/ModuleInfo.java
  deegree-datastores/deegree-coveragestores/deegree-coveragestore-oracle-georaster/pom.xml
  deegree-datastores/deegree-tilestores/deegree-tilestore-remotewms/src/test/java/org/deegree/tile/persistence/remotewms/RemoteWMSTileStoreTest.java
  deegree-services/deegree-webservices-handbook/src/main/sphinx/installation.rst
  pom.xml
Labels: enhancement, in progress

#877 Replaced WFS configuration option allowFeatureReferencesToDatastore by new idGenMode
  deegree-services/deegree-services-wfs/src/main/java/org/deegree/services/wfs/WebFeatureService.java
  deegree-services/deegree-services-wfs/src/main/resources/META-INF/schemas/services/wfs/3.4.0/wfs_configuration.xsd
  deegree-services/deegree-webservices-handbook/src/main/sphinx/webservices.rst
Labels: WFS, enhancement

#879 Fixes several bugs concerning xlink:href attribute
  deegree-core/deegree-core-base/src/main/java/org/deegree/feature/xpath/GMLObjectNavigator.java
  deegree-core/deegree-core-base/src/main/java/org/deegree/gml/feature/GMLFeatureWriter.java
  deegree-core/deegree-core-base/src/test/java/org/deegree/feature/xpath/GMLObjectXPathTest.java
  deegree-core/deegree-core-base/src/test/resources/org/deegree/gml/misc/feature/CustomPropertiesGml32.xml
  deegree-core/deegree-core-base/src/test/resources/org/deegree/gml/misc/schema/CustomPropertiesGml32.xsd
  deegree-datastores/deegree-featurestores/deegree-featurestore-sql/src/main/java/org/deegree/feature/persistence/sql/SQLFeatureStore.java
Labels: bug

#885 Update handbook: Add hint regarding PrebindNamespace
  deegree-services/deegree-webservices-handbook/src/main/sphinx/webservices.rst
Labels: documentation

#803 Enabled support of FeatureCollections as FeatureTypes
  deegree-core/deegree-core-base/src/main/java/org/deegree/feature/types/DynamicFeatureType.java
  deegree-core/deegree-core-base/src/main/java/org/deegree/feature/types/FeatureType.java
  deegree-core/deegree-core-base/src/main/java/org/deegree/feature/types/GenericFeatureCollectionType.java
  deegree-core/deegree-core-base/src/main/java/org/deegree/feature/types/GenericFeatureType.java
  deegree-datastores/deegree-featurestores/deegree-featurestore-sql/src/main/java/org/deegree/feature/persistence/sql/rules/FeatureBuilderRelational.java
  deegree-services/deegree-services-wfs/src/main/java/org/deegree/services/wfs/WfsFeatureStoreManager.java
Labels: bug, in progress

#888 #603 Transferred content from old wiki
  CONTRIB.md
Labels: TMC discussion, documentation

#887 Integrate new tool deegree-tools-config (makes usage of Java 8+ mandatory)
  .travis.yml
  deegree-tools/deegree-tools-config/README.md
  deegree-tools/deegree-tools-config/pom.xml
  deegree-tools/deegree-tools-config/src/main/config/.gitignore
  deegree-tools/deegree-tools-config/src/main/java/org/deegree/tools/config/Exec.java
  deegree-tools/deegree-tools-config/src/main/java/org/deegree/tools/config/PropertyNameParser.java
  deegree-tools/deegree-tools-config/src/main/resources/log4j.properties
  deegree-tools/deegree-tools-config/src/test/java/org/deegree/tools/config/InspireIT.java
  deegree-tools/deegree-tools-config/src/test/java/org/deegree/tools/config/PropertyNameParserTest.java
  deegree-tools/deegree-tools-config/src/test/resources/listOfPropertiesWithPrimitiveHref
  deegree-tools/pom.xml
  pom.xml
Labels: enhancement

#893 Java 8 Updates
  deegree-core/deegree-core-geometry/pom.xml
  deegree-core/deegree-core-sqldialect/deegree-sqldialect-oracle/pom.xml
  deegree-core/deegree-core-sqldialect/deegree-sqldialect-postgis/pom.xml
  deegree-datastores/deegree-coveragestores/deegree-coveragestore-oracle-georaster/pom.xml
  deegree-services/deegree-services-wms/src/main/java/org/deegree/services/wms/controller/WMSControllerBase.java
  deegree-services/deegree-webservices-handbook/src/main/sphinx/featurestores.rst
  deegree-services/deegree-webservices-handbook/src/main/sphinx/installation.rst
  deegree-services/deegree-webservices-handbook/src/main/sphinx/javamodules.rst
  deegree-services/deegree-webservices-handbook/src/main/sphinx/metadatastores.rst
  deegree-services/deegree-webservices-handbook/src/main/sphinx/serverconnections.rst
  deegree-services/deegree-webservices/pom.xml
  deegree-tests/deegree-csw-bkg/pom.xml
  pom.xml
Labels: enhancement

#688 Wms custom format cleanup
  deegree-core/deegree-core-coverage/src/main/java/org/deegree/coverage/raster/io/imageio/geotiff/GeoTiffWriter.java
  deegree-core/deegree-core-rendering-2d/src/main/java/org/deegree/rendering/r2d/ImageSerializer.java
  deegree-core/deegree-core-rendering-2d/src/main/java/org/deegree/rendering/r2d/context/ImageRenderContext.java
  deegree-core/deegree-core-rendering-2d/src/main/java/org/deegree/rendering/r2d/context/RenderingInfo.java
  deegree-services/deegree-services-wms/pom.xml
  deegree-services/deegree-services-wms/src/main/java/org/deegree/services/wms/controller/WMSController.java
  deegree-services/deegree-services-wms/src/main/java/org/deegree/services/wms/controller/plugins/ImageSerializerGeoTiff.java
  deegree-services/deegree-services-wms/src/main/resources/META-INF/schemas/services/wms/3.4.0/wms_configuration.xsd
  deegree-services/deegree-webservices-handbook/src/main/sphinx/webservices.rst
Labels: enhancement, in progress

#896 Fixing travis-ci build error failed to download tomcat artifact
  deegree-services/deegree-webservices-tomcat-bundle/pom.xml
Labels: bug
