Repository deegree/deegree3, pull requests merged in 2019-03, with the labels that each got.

#958 Updating handbook with security how to
  deegree-services/deegree-webservices-handbook/src/main/sphinx/installation.rst
  deegree-services/deegree-webservices-handbook/src/main/sphinx/intro.rst
  deegree-services/deegree-webservices-handbook/src/main/sphinx/restapi.rst
Labels: TMC discussion, documentation

#960 Fixed NPE if ServiceProvider is missing
  deegree-services/deegree-services-commons/src/main/java/org/deegree/services/ows/capabilities/OWSCapabilitiesXMLAdapter.java
Labels: WFS, bug

#952 Fixed position of DecimalCoordinateFormatter
  deegree-services/deegree-webservices-handbook/src/main/sphinx/xml/wfs_gmlformat.xml
Labels: bug, documentation

#940 Improve exception handling concerning bbox cache properties
  deegree-datastores/deegree-featurestores/deegree-featurestore-commons/src/main/java/org/deegree/feature/persistence/BBoxTracker.java
  deegree-datastores/deegree-featurestores/deegree-featurestore-commons/src/main/java/org/deegree/feature/persistence/cache/BBoxPropertiesCache.java
Labels: enhancement

#950 Updated legal section in Contribution Guidelines
  CONTRIB.md
  CONTRIBUTORS.md
  README.md
Labels: TMC discussion, documentation, enhancement
