Repository deegree/deegree3, pull requests merged in 2019-12, with the labels that each got.

#777 Enhanced Response Paging regarding resultType="hits"
  deegree-services/deegree-services-wfs/src/main/java/org/deegree/services/wfs/format/gml/request/GmlGetFeatureHandler.java
Labels: enhancement

#1004 Enhanced implementation for WFS 2.0 response paging
  deegree-core/deegree-core-sqldialect/deegree-sqldialect-commons/src/main/java/org/deegree/sqldialect/SQLDialect.java
  deegree-core/deegree-core-sqldialect/deegree-sqldialect-mssql/src/main/java/org/deegree/sqldialect/mssql/MSSQLDialect.java
  deegree-datastores/deegree-featurestores/deegree-featurestore-commons/src/main/java/org/deegree/feature/persistence/FeatureStore.java
  deegree-datastores/deegree-featurestores/deegree-featurestore-commons/src/main/java/org/deegree/feature/persistence/query/Query.java
  deegree-datastores/deegree-featurestores/deegree-featurestore-memory/src/main/java/org/deegree/feature/persistence/memory/MemoryFeatureStore.java
  deegree-datastores/deegree-featurestores/deegree-featurestore-remotewfs/src/main/java/org/deegree/feature/persistence/remotewfs/RemoteWFSFeatureStore.java
  deegree-datastores/deegree-featurestores/deegree-featurestore-shape/src/main/java/org/deegree/feature/persistence/shape/ShapeFeatureStore.java
  deegree-datastores/deegree-featurestores/deegree-featurestore-simplesql/src/main/java/org/deegree/feature/persistence/simplesql/SimpleSQLFeatureStore.java
  deegree-datastores/deegree-featurestores/deegree-featurestore-sql/src/main/java/org/deegree/feature/persistence/sql/SQLFeatureStore.java
  deegree-services/deegree-services-wfs/src/main/java/org/deegree/services/wfs/format/gml/request/GmlGetFeatureHandler.java
  deegree-services/deegree-services-wfs/src/main/java/org/deegree/services/wfs/query/QueryAnalyzer.java
Labels: WFS, enhancement

#1019 Add Jenkinsfile for Jenkins CI to repository
  Jenkinsfile
  deegree-tests/deegree-compliance-tests/pom.xml
  deegree-tests/deegree-csw-bkg/pom.xml
  deegree-tests/deegree-wms-similarity-tests/pom.xml
  deegree-tests/deegree-wms-tiling-tests/pom.xml
  deegree-tests/deegree-wmts-tests/pom.xml
  deegree-tests/deegree-workspace-tests/pom.xml
  pom.xml
Labels: enhancement

#1007 Update handbook regarding support of Extended Capabilities in WMS 1.1.1
  deegree-services/deegree-webservices-handbook/src/main/asciidoc/webservices.adoc
Labels: documentation

#930 Upgraded compiler plugin to 3.8.1
  pom.xml
Labels: enhancement, ready
