Repository deegree/deegree3, pull requests merged in 2019-06, with the labels that each got.

#987 Fix incomplete implementation of proxy authentication
  deegree-core/deegree-core-commons/src/main/java/org/deegree/commons/proxy/ProxySettings.java
Labels: bug

#986 Fix NPE in exception serializer if exception is NPE
  deegree-services/deegree-services-commons/src/main/java/org/deegree/services/ows/PreOWSExceptionReportSerializer.java
Labels: WFS, WMS, bug

#935 Fixes "Too many open files" in case external resources are not available
  deegree-core/deegree-core-base/src/main/java/org/deegree/gml/GMLInputFactory.java
Labels: WFS, bug
