Repository deegree/deegree3, pull requests merged in 2020-12, with the labels that each got.

#1098 #1096 set failing tests to ignore, this is a temporary solution
  deegree-tests/deegree-resource-deps-tests/src/test/java/org/deegree/workspace/SimpleSqlFeatureStoreTest.java
Labels: CI and build, bug

#1092 Make gml:id attribute optional as defined in updated GML 3.2.1 schemas
  deegree-core/deegree-core-base/src/main/java/org/deegree/gml/commons/AbstractGMLObjectReader.java
  deegree-core/deegree-core-base/src/test/java/org/deegree/gml/schema/GMLAppSchemaReaderTest.java
  deegree-core/deegree-core-protocol/deegree-protocol-wfs/src/test/java/org/deegree/protocol/wfs/describefeaturetype/xml/DescribeFeatureTypeXMLAdapterTest.java
  deegree-core/deegree-core-protocol/deegree-protocol-wfs/src/test/resources/org/deegree/protocol/wfs/describefeaturetype/xml/wfs200/DescribeFeatureType_Example01_Request.xml
  deegree-core/deegree-core-protocol/deegree-protocol-wfs/src/test/resources/org/deegree/protocol/wfs/describefeaturetype/xml/wfs200/DescribeFeatureType_Example02_Request.xml
  pom.xml
Labels: enhancement

#1084 Fix cache handling of raster files
  deegree-core/deegree-core-coverage/src/main/java/org/deegree/coverage/raster/cache/RasterCache.java
  deegree-core/deegree-core-coverage/src/main/java/org/deegree/coverage/raster/io/imageio/IIORasterDataReader.java
  deegree-core/deegree-core-coverage/src/main/java/org/deegree/coverage/raster/io/imageio/IIORasterReader.java
  deegree-core/deegree-core-coverage/src/main/java/org/deegree/coverage/raster/io/jai/JAIRasterReader.java
  deegree-core/deegree-core-rendering-2d/src/main/java/org/deegree/rendering/r2d/legends/LegendBuilder.java
  deegree-services/deegree-services-wms/src/main/java/org/deegree/services/wms/GetLegendHandler.java
  deegree-services/deegree-webservices-handbook/src/main/asciidoc/coveragestores.adoc
Labels: bug, enhancement

#1086 Make DPI parameter parsing more compatible
  deegree-core/deegree-core-commons/src/main/java/org/deegree/commons/utils/StringUtils.java
  deegree-core/deegree-core-protocol/deegree-protocol-wms/src/main/java/org/deegree/protocol/wms/filter/EnvFunction.java
  deegree-core/deegree-core-protocol/deegree-protocol-wms/src/main/java/org/deegree/protocol/wms/map/GetMapParser.java
  deegree-core/deegree-core-protocol/deegree-protocol-wms/src/main/java/org/deegree/protocol/wms/ops/GetMap.java
  deegree-core/deegree-core-protocol/deegree-protocol-wms/src/main/resources/META-INF/services/org.deegree.filter.function.FunctionProvider
  deegree-services/deegree-services-wms/src/main/java/org/deegree/services/wms/MapService.java
  deegree-services/deegree-webservices-handbook/src/main/asciidoc/filterencoding.adoc
  deegree-tests/deegree-wms-similarity-tests/src/main/webapp/WEB-INF/workspace/data/utah/Satellite_Provo_cut.tiff
  deegree-tests/deegree-wms-similarity-tests/src/main/webapp/WEB-INF/workspace/datasources/coverage/utah_satellite_provo.xml
  deegree-tests/deegree-wms-similarity-tests/src/main/webapp/WEB-INF/workspace/layers/contours.xml
  deegree-tests/deegree-wms-similarity-tests/src/main/webapp/WEB-INF/workspace/layers/satellite_provo.xml
  deegree-tests/deegree-wms-similarity-tests/src/main/webapp/WEB-INF/workspace/themes/theme.xml
  deegree-tests/deegree-wms-similarity-tests/src/test/requests/resolution/contours_parameter_dpi.kvp
  deegree-tests/deegree-wms-similarity-tests/src/test/requests/resolution/contours_parameter_dpi.response
  deegree-tests/deegree-wms-similarity-tests/src/test/requests/resolution/contours_parameter_format_options.kvp
  deegree-tests/deegree-wms-similarity-tests/src/test/requests/resolution/contours_parameter_format_options.response
  deegree-tests/deegree-wms-similarity-tests/src/test/requests/resolution/contours_parameter_map_resolution.kvp
  deegree-tests/deegree-wms-similarity-tests/src/test/requests/resolution/contours_parameter_map_resolution.response
  deegree-tests/deegree-wms-similarity-tests/src/test/requests/resolution/contours_parameter_pixelsize.kvp
  deegree-tests/deegree-wms-similarity-tests/src/test/requests/resolution/contours_parameter_pixelsize.response
  deegree-tests/deegree-wms-similarity-tests/src/test/requests/resolution/contours_parameter_res.kvp
  deegree-tests/deegree-wms-similarity-tests/src/test/requests/resolution/contours_parameter_res.response
  deegree-tests/deegree-wms-similarity-tests/src/test/requests/resolution/contours_parameter_x-dpi.kvp
  deegree-tests/deegree-wms-similarity-tests/src/test/requests/resolution/contours_parameter_x-dpi.response
  deegree-tests/deegree-wms-similarity-tests/src/test/requests/resolution/contours_vector_dpi_100_empty.kvp
  deegree-tests/deegree-wms-similarity-tests/src/test/requests/resolution/contours_vector_dpi_100_empty.response
  deegree-tests/deegree-wms-similarity-tests/src/test/requests/resolution/contours_vector_dpi_192.kvp
  deegree-tests/deegree-wms-similarity-tests/src/test/requests/resolution/contours_vector_dpi_192.response
  deegree-tests/deegree-wms-similarity-tests/src/test/requests/resolution/contours_vector_dpi_96.kvp
  deegree-tests/deegree-wms-similarity-tests/src/test/requests/resolution/contours_vector_dpi_96.response
  deegree-tests/deegree-wms-similarity-tests/src/test/requests/resolution/contours_vector_dpi_default_empty.kvp
  deegree-tests/deegree-wms-similarity-tests/src/test/requests/resolution/contours_vector_dpi_default_empty.response
  deegree-tests/deegree-wms-similarity-tests/src/test/requests/resolution/satellite_provo_dpi_100_empty.kvp
  deegree-tests/deegree-wms-similarity-tests/src/test/requests/resolution/satellite_provo_dpi_100_empty.response
  deegree-tests/deegree-wms-similarity-tests/src/test/requests/resolution/satellite_provo_dpi_192.kvp
  deegree-tests/deegree-wms-similarity-tests/src/test/requests/resolution/satellite_provo_dpi_192.response
  deegree-tests/deegree-wms-similarity-tests/src/test/requests/resolution/satellite_provo_dpi_96.kvp
  deegree-tests/deegree-wms-similarity-tests/src/test/requests/resolution/satellite_provo_dpi_96.response
  deegree-tests/deegree-wms-similarity-tests/src/test/requests/resolution/satellite_provo_dpi_default_empty.kvp
  deegree-tests/deegree-wms-similarity-tests/src/test/requests/resolution/satellite_provo_dpi_default_empty.response
Labels: enhancement

#1107 Fixes some layout and formatting issue in handbook
  deegree-services/deegree-webservices-handbook/pom.xml
  deegree-services/deegree-webservices-handbook/src/main/asciidoc/basics.adoc
  deegree-services/deegree-webservices-handbook/src/main/asciidoc/featurestores.adoc
  deegree-services/deegree-webservices-handbook/src/main/asciidoc/filterencoding.adoc
  deegree-services/deegree-webservices-handbook/src/main/asciidoc/renderstyles.adoc
  deegree-services/deegree-webservices-handbook/src/main/asciidoc/webservices.adoc
  pom.xml
Labels: documentation, enhancement

#1032 Fixes deegree web admin console showing stack trace in case of session timeout
  deegree-services/deegree-webservices/src/main/webapp/WEB-INF/faces-config.xml
  deegree-services/deegree-webservices/src/main/webapp/WEB-INF/web.xml
  deegree-services/deegree-webservices/src/main/webapp/index.xhtml
  deegree-services/deegree-webservices/src/main/webapp/layout.xhtml
  deegree-services/deegree-webservices/src/main/webapp/menu.xhtml
Labels: bug, console

#931 Removed obsolete and outdated JavaCheck class
  deegree-misc/deegree-javacheck/pom.xml
  deegree-misc/deegree-javacheck/src/main/java/org/deegree/JavaCheck.java
  deegree-misc/pom.xml
  deegree-services/deegree-webservices-handbook/src/main/asciidoc/installation.adoc
  deegree-services/deegree-webservices-tomcat-bundle/pom.xml
  deegree-services/deegree-webservices-tomcat-bundle/src/main/assembly/distribution-assembly.xml
  deegree-services/deegree-webservices-tomcat-bundle/src/main/resources/start-deegree-linux.sh
  deegree-services/deegree-webservices-tomcat-bundle/src/main/resources/start-deegree-osx.cmd
  deegree-services/deegree-webservices-tomcat-bundle/src/main/resources/start-deegree-windows.bat
  pom.xml
Labels: enhancement, in progress, needs rebase
