Repository deegree/deegree3, pull requests merged in 2020-08, with the labels that each got.

#734 Enhanced WFS for support of CreateStoredQueries and DropStoredQuery
  deegree-core/deegree-core-commons/src/main/java/org/deegree/commons/ows/exception/OWSException.java
  deegree-core/deegree-core-protocol/deegree-protocol-wfs/pom.xml
  deegree-core/deegree-core-protocol/deegree-protocol-wfs/src/main/java/org/deegree/protocol/wfs/storedquery/xml/StoredQueryDefinition200Encoder.java
  deegree-core/deegree-core-protocol/deegree-protocol-wfs/src/test/java/org/deegree/protocol/wfs/storedquery/xml/StoredQueryDefinition200EncoderTest.java
  deegree-core/deegree-core-protocol/deegree-protocol-wfs/src/test/resources/org/deegree/protocol/wfs/storedquery/xml/storedQuery.xml
  deegree-services/deegree-services-commons/src/main/java/org/deegree/services/ows/OWS110ExceptionReportSerializer.java
  deegree-services/deegree-services-wfs/pom.xml
  deegree-services/deegree-services-wfs/src/main/java/org/deegree/services/wfs/GetCapabilitiesHandler.java
  deegree-services/deegree-services-wfs/src/main/java/org/deegree/services/wfs/WebFeatureService.java
  deegree-services/deegree-services-wfs/src/main/java/org/deegree/services/wfs/query/StoredQueryHandler.java
  deegree-services/deegree-services-wfs/src/test/java/org/deegree/services/wfs/query/StoredQueryHandlerTest.java
  deegree-services/deegree-services-wfs/src/test/resources/org/deegree/services/wfs/query/storedQuery_byName.xml
  deegree-services/deegree-services-wfs/src/test/resources/org/deegree/services/wfs/query/storedQuery_erroneous.xml
  deegree-services/deegree-webservices-handbook/src/main/asciidoc/basics.adoc
  deegree-services/deegree-webservices-handbook/src/main/asciidoc/webservices.adoc
Labels: documentation, enhancement, ready

#1056 Fix WFS GetFeature request with multiple queries
  deegree-core/deegree-core-base/pom.xml
  deegree-core/deegree-core-base/src/main/java/org/deegree/gml/GMLStreamWriter.java
  deegree-core/deegree-core-base/src/main/java/org/deegree/gml/feature/GMLFeatureWriter.java
  deegree-core/deegree-core-base/src/test/java/org/deegree/gml/feature/GMLFeatureWriterTest.java
  deegree-services/deegree-services-wfs/src/main/java/org/deegree/services/wfs/format/gml/request/GmlGetFeatureHandler.java
  deegree-services/deegree-services-wfs/src/main/java/org/deegree/services/wfs/query/QueryAnalyzer.java
  deegree-services/deegree-services-wfs/src/test/java/org/deegree/services/wfs/query/QueryAnalyzerTest.java
  pom.xml
Labels: WFS, bug

#1057 Support of SQLFeatureStore configurations in subfolders
  deegree-core/deegree-core-style/src/main/java/org/deegree/style/persistence/sld/SldStyleStoreBuilder.java
  deegree-core/deegree-core-workspace/src/main/java/org/deegree/workspace/ResourceLocation.java
  deegree-core/deegree-core-workspace/src/main/java/org/deegree/workspace/standard/DefaultLocationHandler.java
  deegree-core/deegree-core-workspace/src/main/java/org/deegree/workspace/standard/DefaultResourceLocation.java
  deegree-datastores/deegree-featurestores/deegree-featurestore-sql/src/main/java/org/deegree/feature/persistence/sql/SqlFeatureStoreBuilder.java
Labels: WFS, enhancement
