Repository deegree/deegree3, pull requests merged in 2020-07, with the labels that each got.

#1068 Export original XML schema if exactly one local schema is configured
  deegree-core/deegree-core-base/src/main/java/org/deegree/gml/schema/GMLAppSchemaWriter.java
  deegree-core/deegree-core-base/src/test/java/org/deegree/gml/schema/GMLAppSchemaWriterTest.java
  deegree-core/deegree-core-commons/src/main/java/org/deegree/commons/xml/schema/SchemaUtils.java
  deegree-services/deegree-services-wfs/src/main/java/org/deegree/services/wfs/format/gml/request/GmlDescribeFeatureTypeHandler.java
Labels: WFS, enhancement, ready

#1048 enhance similarity test for easier problem solving
  deegree-core/deegree-core-commons/src/main/java/org/deegree/commons/utils/test/IntegrationTestUtils.java
  deegree-core/deegree-core-rendering-2d/src/test/java/org/deegree/rendering/r2d/AbstractSimilarityTest.java
  deegree-core/deegree-core-rendering-2d/src/test/java/org/deegree/rendering/r2d/Java2DRendererTest.java
  deegree-core/deegree-core-rendering-2d/src/test/resources/org/deegree/rendering/r2d/renderertest/linestyling.png
  deegree-core/deegree-core-rendering-2d/src/test/resources/org/deegree/rendering/r2d/renderertest/linestyling2.png
  deegree-core/deegree-core-rendering-2d/src/test/resources/org/deegree/rendering/r2d/renderertest/linestylingsmallclipping.png
  deegree-core/deegree-core-rendering-2d/src/test/resources/org/deegree/rendering/r2d/renderertest/pointstyling.png
  deegree-core/deegree-core-rendering-2d/src/test/resources/org/deegree/rendering/r2d/renderertest/polygonstyling.png
  deegree-core/deegree-core-rendering-2d/src/test/resources/org/deegree/rendering/r2d/renderertest/polygonstylingperpendicularoffset.png
  deegree-core/deegree-core-rendering-2d/src/test/resources/org/deegree/rendering/r2d/renderertest/polygonstylingsmallclipping.png
  deegree-core/deegree-core-rendering-2d/src/test/resources/org/deegree/rendering/r2d/renderertest/polygonstylingwithcircelssmallclipping.png
  deegree-core/deegree-core-rendering-2d/src/test/resources/org/deegree/rendering/r2d/renderertest/polygonstylingwithstrokewithoutsize.png
  deegree-core/deegree-core-rendering-2d/src/test/resources/org/deegree/rendering/r2d/renderertest/textstyling.png
  deegree-core/deegree-core-rendering-2d/src/test/resources/org/deegree/rendering/r2d/renderertest/textstyling2.png
  deegree-tests/deegree-wms-remoteows-tests/src/test/java/org/deegree/services/wms/RemoteWMSIntegrationTest.java
  deegree-tests/deegree-wms-similarity-tests/src/test/java/org/deegree/services/wms/WMSSimilarityIntegrationTest.java
Labels: enhancement

#1076 Enhance Image Similarity Test
  deegree-core/deegree-core-rendering-2d/src/test/java/org/deegree/rendering/r2d/AbstractSimilarityTest.java
  deegree-core/deegree-core-rendering-2d/src/test/java/org/deegree/rendering/r2d/Java2DRendererTest.java
  deegree-tests/deegree-wms-similarity-tests/src/test/java/org/deegree/services/wms/WMSSimilarityIntegrationTest.java
Labels: CI and build, enhancement
