Repository deegree/deegree3, pull requests merged in 2021-12, with the labels that each got.

#1216 Add check of transparent parameter
  deegree-core/deegree-core-protocol/deegree-protocol-wms/src/main/java/org/deegree/protocol/wms/ops/GetMap.java
  deegree-core/deegree-core-protocol/deegree-protocol-wms/src/test/java/org/deegree/protocol/wms/ops/GetMapTest.java
  deegree-services/deegree-services-wms/src/main/java/org/deegree/services/wms/controller/WMSController.java
Labels: bug, WMS

#1127 SchemaLocation points to GML 3.2.2 when GML 3.2.1 is requested
  deegree-services/deegree-services-wfs/src/main/java/org/deegree/services/wfs/format/gml/request/AbstractGmlRequestHandler.java
Labels: bug, WFS

#1227 Moved module deegree-spring to uncoupled
  pom.xml
  uncoupled/deegree-spring/pom.xml
  uncoupled/deegree-spring/src/main/java/org/deegree/spring/AbstractSpringResourceBuilder.java
  uncoupled/deegree-spring/src/main/java/org/deegree/spring/ApplicationContextHolder.java
  uncoupled/deegree-spring/src/main/java/org/deegree/spring/ApplicationContextHolderManager.java
  uncoupled/deegree-spring/src/main/java/org/deegree/spring/ApplicationContextHolderProvider.java
  uncoupled/deegree-spring/src/main/java/org/deegree/spring/GenericSpringResourceBuilder.java
  uncoupled/deegree-spring/src/main/java/org/deegree/spring/GenericSpringResourceMetadata.java
  uncoupled/deegree-spring/src/main/java/org/deegree/spring/annotation/InjectMetadata.java
  uncoupled/deegree-spring/src/main/java/org/deegree/spring/bootstrap/BootstrapApplicationContextHolderBuilder.java
  uncoupled/deegree-spring/src/main/java/org/deegree/spring/bootstrap/BootstrapApplicationContextHolderMetadata.java
  uncoupled/deegree-spring/src/main/java/org/deegree/spring/bootstrap/BootstrapApplicationContextHolderProvider.java
  uncoupled/deegree-spring/src/main/java/org/deegree/spring/db/SpringConnectionProvider.java
  uncoupled/deegree-spring/src/main/java/org/deegree/spring/db/SpringConnectionProviderBuilder.java
  uncoupled/deegree-spring/src/main/java/org/deegree/spring/db/SpringConnectionProviderMetadata.java
  uncoupled/deegree-spring/src/main/java/org/deegree/spring/db/SpringConnectionProviderProvider.java
  uncoupled/deegree-spring/src/main/java/org/deegree/spring/layer/SpringLayerStoreProvider.java
  uncoupled/deegree-spring/src/main/java/org/deegree/spring/services/SpringOWSMetadataProviderProvider.java
  uncoupled/deegree-spring/src/main/resources/META-INF/schemas/spring/3.4.0/bootstrap.xsd
  uncoupled/deegree-spring/src/main/resources/META-INF/schemas/spring/3.4.0/db.xsd
  uncoupled/deegree-spring/src/main/resources/META-INF/schemas/spring/3.4.0/generic.xsd
  uncoupled/deegree-spring/src/main/resources/META-INF/schemas/spring/3.4.0/layer.xsd
  uncoupled/deegree-spring/src/main/resources/META-INF/schemas/spring/3.4.0/metadata.xsd
  uncoupled/deegree-spring/src/main/resources/META-INF/services/org.deegree.db.ConnectionProviderProvider
  uncoupled/deegree-spring/src/main/resources/META-INF/services/org.deegree.layer.persistence.LayerStoreProvider
  uncoupled/deegree-spring/src/main/resources/META-INF/services/org.deegree.services.metadata.provider.OWSMetadataProviderProvider
  uncoupled/deegree-spring/src/main/resources/META-INF/services/org.deegree.spring.ApplicationContextHolderProvider
  uncoupled/deegree-spring/src/main/resources/META-INF/services/org.deegree.workspace.ResourceManager
  uncoupled/deegree-spring/src/test/java/org/deegree/spring/AbstractSpringResourceBuilderTest.java
  uncoupled/deegree-spring/src/test/java/org/deegree/spring/GenericSpringResourceBuilderTest.java
  uncoupled/deegree-spring/src/test/java/org/deegree/spring/TestContext.java
  uncoupled/deegree-spring/src/test/java/org/deegree/spring/test/jaxb/ObjectFactory.java
  uncoupled/deegree-spring/src/test/java/org/deegree/spring/test/jaxb/TestConfig.java
  uncoupled/deegree-spring/src/test/resources/org/deegree/spring/test.xml
Labels: enhancement

#1230 Added log4j configuration files for WMS and WMTS integration tests
  deegree-tests/deegree-wms-similarity-tests/src/test/resources/log4j.properties
  deegree-tests/deegree-wmts-tests/src/test/resources/log4j.properties
Labels: enhancement, CI and build

#1221 Enhancement of the deegree WMTS documentation
  deegree-services/deegree-webservices-handbook/src/main/asciidoc/webservices.adoc
Labels: enhancement, documentation, WMTS

#1125 Add myself to CONTRIBUTORS.md
  CONTRIBUTORS.md
Labels: documentation

#1031 Upgrade Jersey to 1.19.4 and commons-fileupload to 1.4
  pom.xml
Labels: enhancement, dependencies

#1247 Upgrade to Apache Log4j2 2.16.0
  deegree-core/deegree-core-annotations/pom.xml
  deegree-core/deegree-core-annotations/src/main/java/org/deegree/commons/annotations/LoggingNotes.java
  deegree-core/deegree-core-annotations/src/main/java/org/deegree/commons/annotations/PackageLoggingNotes.java
  deegree-core/deegree-core-annotations/src/main/java/org/deegree/commons/annotations/Tool.java
  deegree-core/deegree-core-annotations/src/main/java/org/deegree/commons/log4j/DuplicateMessageFilter.java
  deegree-core/deegree-core-annotations/src/main/java/org/deegree/commons/processors/LoggingAnnotationProcessor.java
  deegree-core/deegree-core-annotations/src/main/java/org/deegree/commons/utils/io/RollbackPrintWriter.java
  deegree-core/deegree-core-annotations/src/main/resources/META-INF/services/javax.annotation.processing.Processor
  deegree-core/deegree-core-annotations/src/main/resources/log4j.properties
  deegree-core/deegree-core-annotations/src/main/resources/log4j2.xml
  deegree-core/deegree-core-commons/pom.xml
  deegree-core/deegree-core-workspace/pom.xml
  deegree-services/deegree-services-commons/pom.xml
  deegree-services/deegree-services-commons/src/api/java/org/deegree/services/controller/OGCFrontController.java
  deegree-services/deegree-webservices-handbook/src/main/asciidoc/basics.adoc
  deegree-services/deegree-webservices-handbook/src/main/asciidoc/index.adoc
  deegree-services/deegree-webservices-handbook/src/main/asciidoc/logging.adoc
  deegree-services/deegree-webservices/pom.xml
  deegree-services/deegree-webservices/src/main/resources/log4j.properties
  deegree-services/deegree-webservices/src/main/resources/log4j2.properties
  deegree-tests/deegree-compliance-tests/pom.xml
  deegree-tests/deegree-compliance-tests/src/main/resources/log4j.properties
  deegree-tests/deegree-compliance-tests/src/test/resources/log4j.properties
  deegree-tests/deegree-compliance-tests/src/test/resources/log4j2.properties
  deegree-tests/deegree-wms-remoteows-tests/pom.xml
  deegree-tests/deegree-wms-remoteows-tests/src/main/resources/log4j.properties
  deegree-tests/deegree-wms-remoteows-tests/src/test/resources/log4j2.properties
  deegree-tests/deegree-wms-similarity-tests/pom.xml
  deegree-tests/deegree-wms-similarity-tests/src/main/resources/log4j.properties
  deegree-tests/deegree-wms-similarity-tests/src/test/resources/log4j.properties
  deegree-tests/deegree-wms-similarity-tests/src/test/resources/log4j2.properties
  deegree-tests/deegree-wmts-tests/pom.xml
  deegree-tests/deegree-wmts-tests/src/main/resources/log4j.properties
  deegree-tests/deegree-wmts-tests/src/test/resources/log4j.properties
  deegree-tests/deegree-wmts-tests/src/test/resources/log4j2.properties
  deegree-tests/deegree-workspace-tests/pom.xml
  deegree-tests/deegree-workspace-tests/src/test/resources/log4j.properties
  deegree-tests/deegree-workspace-tests/src/test/resources/log4j2.properties
  deegree-tools/deegree-tools-3d/pom.xml
  deegree-tools/deegree-tools-3d/src/main/config/log4j.properties
  deegree-tools/deegree-tools-3d/src/main/config/log4j2.properties
  deegree-tools/deegree-tools-base/pom.xml
  deegree-tools/deegree-tools-base/src/main/config/log4j.properties
  deegree-tools/deegree-tools-base/src/main/config/log4j2.properties
  pom.xml
Labels: enhancement, documentation, CVE, dependencies

#1243 Fixed Shape files for workspace used by WMS integration tests
  deegree-tests/deegree-wms-similarity-tests/src/main/webapp/WEB-INF/workspace/data/utah/SGID024_Springs.dbf
  deegree-tests/deegree-wms-similarity-tests/src/main/webapp/WEB-INF/workspace/data/utah/SGID024_Springs.shx
  deegree-tests/deegree-wms-similarity-tests/src/main/webapp/WEB-INF/workspace/data/utah/SGID500_Contours500Ft.dbf
  deegree-tests/deegree-wms-similarity-tests/src/main/webapp/WEB-INF/workspace/data/utah/SGID500_Contours500Ft.shx
  deegree-tests/deegree-wms-similarity-tests/src/main/webapp/WEB-INF/workspace/data/utah/SGID500_DominantVegetation.dbf
  deegree-tests/deegree-wms-similarity-tests/src/main/webapp/WEB-INF/workspace/data/utah/SGID500_DominantVegetation.shx
  deegree-tests/deegree-wms-similarity-tests/src/main/webapp/WEB-INF/workspace/data/utah/ttfsymbol.dbf
  deegree-tests/deegree-wms-similarity-tests/src/main/webapp/WEB-INF/workspace/data/utah/ttfsymbol.shx
Labels: enhancement, CI and build, workspace

#1244 Upgrade to JTS 1.18.2
  deegree-tests/deegree-wms-similarity-tests/src/main/webapp/WEB-INF/workspace/data/utah/SGID024_Springs.dbf
  deegree-tests/deegree-wms-similarity-tests/src/main/webapp/WEB-INF/workspace/data/utah/SGID024_Springs.shx
  deegree-tests/deegree-wms-similarity-tests/src/main/webapp/WEB-INF/workspace/data/utah/SGID500_Contours500Ft.dbf
  deegree-tests/deegree-wms-similarity-tests/src/main/webapp/WEB-INF/workspace/data/utah/SGID500_Contours500Ft.shx
  deegree-tests/deegree-wms-similarity-tests/src/main/webapp/WEB-INF/workspace/data/utah/SGID500_DominantVegetation.dbf
  deegree-tests/deegree-wms-similarity-tests/src/main/webapp/WEB-INF/workspace/data/utah/SGID500_DominantVegetation.shp
  deegree-tests/deegree-wms-similarity-tests/src/main/webapp/WEB-INF/workspace/data/utah/SGID500_DominantVegetation.shx
  deegree-tests/deegree-wms-similarity-tests/src/main/webapp/WEB-INF/workspace/data/utah/ttfsymbol.dbf
  deegree-tests/deegree-wms-similarity-tests/src/main/webapp/WEB-INF/workspace/data/utah/ttfsymbol.shx
  pom.xml
Labels: enhancement, dependencies

#1239 Improved handling of strict parameter only if geometry parameter is passed
  deegree-datastores/deegree-featurestores/deegree-featurestore-sql/src/main/java/org/deegree/feature/persistence/sql/xpath/MappedXPath.java
Labels: bug, WFS

#1240 WMS 1.3: Throw exception when using invalid service parameter in GetCapabilities request
  deegree-services/deegree-services-wms/src/main/java/org/deegree/services/wms/controller/WMSController.java
Labels: bug, WMS

#1241 WMS 1.3: Throw correct exception type when requesting erroneous version in GetMap request
  deegree-services/deegree-services-wms/src/main/java/org/deegree/services/wms/controller/WMSController.java
Labels: bug, WMS
