Repository deegree/deegree3, pull requests merged in 2021-09, with the labels that each got.

#1152 Migrated findbugs plugin to spotbugs plugin
  Jenkinsfile
  pom.xml
Labels: enhancement, dependencies

#1166 Minor improvements of deegree webservice handbook
  deegree-services/deegree-webservices-handbook/pom.xml
  deegree-services/deegree-webservices-handbook/src/main/asciidoc/installation.adoc
  deegree-services/deegree-webservices-handbook/src/main/asciidoc/intro.adoc
  deegree-services/deegree-webservices-handbook/src/main/asciidoc/layers.adoc
  deegree-services/deegree-webservices-handbook/src/main/asciidoc/metadatastores.adoc
  deegree-services/deegree-webservices-handbook/src/main/asciidoc/webservices.adoc
  pom.xml
Labels: bug, documentation

#1185 Create FUNDING.yml
  .github/FUNDING.yml
Labels: TMC discussion, website
