Repository deegree/deegree3, pull requests merged in 2022-06, with the labels that each got.

#1343 Create schema assembly as single zip artifact
  deegree-core/deegree-core-schema/README.md
  deegree-core/deegree-core-schema/pom.xml
  deegree-core/deegree-core-schema/src/main/assembly/schemas.xml
  deegree-core/pom.xml
  deegree-workspaces/deegree-workspace-aixm/pom.xml
  deegree-workspaces/deegree-workspace-compliance-tests/pom.xml
  deegree-workspaces/deegree-workspace-csw-memory-tests/pom.xml
  deegree-workspaces/deegree-workspace-csw/pom.xml
  deegree-workspaces/deegree-workspace-geosciml/pom.xml
  deegree-workspaces/deegree-workspace-utah/pom.xml
  deegree-workspaces/deegree-workspace-wcts/pom.xml
  deegree-workspaces/deegree-workspace-wps/pom.xml
  deegree-workspaces/pom.xml
  pom.xml
Labels: enhancement, website, CI and build

#1342 Prepare pipeline for v3.5
  Jenkinsfile
  README.md
  SECURITY.md
Labels: enhancement, documentation, CI and build

#1164 Implementation of GeoJsonSingleFeatureWriter
  deegree-core/deegree-core-base/pom.xml
  deegree-core/deegree-core-base/src/main/java/org/deegree/geojson/GeoJsonFeatureWriter.java
  deegree-core/deegree-core-base/src/main/java/org/deegree/geojson/GeoJsonGeometryWriter.java
  deegree-core/deegree-core-base/src/main/java/org/deegree/geojson/GeoJsonSingleFeatureWriter.java
  deegree-core/deegree-core-base/src/main/java/org/deegree/geojson/GeoJsonWriter.java
  deegree-core/deegree-core-base/src/test/java/org/deegree/geojson/GeoJsonFeatureWriterTest.java
  deegree-core/deegree-core-base/src/test/java/org/deegree/geojson/GeoJsonGeometryWriterTest.java
  deegree-core/deegree-core-base/src/test/resources/org/deegree/geojson/CadastralZoning.gml
  deegree-core/deegree-core-base/src/test/resources/org/deegree/geojson/CadastralZoningWithArrays.gml
  deegree-core/deegree-core-base/src/test/resources/org/deegree/geojson/CadastralZoningWithPrimitiveArray.gml
  deegree-core/deegree-core-base/src/test/resources/org/deegree/geojson/micado_kennzahlen_v1_2.xsd
  deegree-core/deegree-core-base/src/test/resources/org/deegree/geojson/zeitreihe.gml
  deegree-core/deegree-core-base/src/test/resources/org/deegree/geojson/zeitreihe.xsd
  deegree-core/deegree-core-base/src/test/resources/org/deegree/geojson/zeitreihen_v1.xsd
  deegree-core/deegree-core-base/src/test/resources/org/deegree/geojson/zuwanderung.gml
  deegree-core/deegree-core-cs/src/main/resources/org/deegree/cs/persistence/deegree/d3/config/crs-definitions.xml
  deegree-datastores/deegree-featurestores/deegree-featurestore-commons/src/main/java/org/deegree/feature/persistence/FeatureStore.java
  deegree-datastores/deegree-featurestores/deegree-featurestore-memory/src/main/java/org/deegree/feature/persistence/memory/MemoryFeatureStore.java
  deegree-datastores/deegree-featurestores/deegree-featurestore-remotewfs/src/main/java/org/deegree/feature/persistence/remotewfs/RemoteWFSFeatureStore.java
  deegree-datastores/deegree-featurestores/deegree-featurestore-shape/src/main/java/org/deegree/feature/persistence/shape/ShapeFeatureStore.java
  deegree-datastores/deegree-featurestores/deegree-featurestore-simplesql/src/main/java/org/deegree/feature/persistence/simplesql/SimpleSQLFeatureStore.java
  deegree-datastores/deegree-featurestores/deegree-featurestore-sql/src/main/java/org/deegree/feature/persistence/sql/SQLFeatureStore.java
  deegree-services/deegree-services-commons/src/main/java/org/deegree/services/metadata/provider/DefaultOwsMetadataProviderBuilder.java
  deegree-services/deegree-services-commons/src/main/resources/META-INF/schemas/services/metadata/metadata.xsd
  deegree-services/deegree-services-wfs/src/main/java/org/deegree/services/wfs/WebFeatureService.java
  deegree-services/deegree-services-wfs/src/main/java/org/deegree/services/wfs/format/geojson/GeoJsonFormat.java
  deegree-services/deegree-services-wfs/src/main/java/org/deegree/services/wfs/format/geojson/request/GeoJsonGetFeatureHandler.java
  deegree-services/deegree-services-wfs/src/main/java/org/deegree/services/wfs/query/QueryAnalyzer.java
  deegree-services/deegree-services-wfs/src/main/resources/META-INF/schemas/services/wfs/wfs_configuration.xsd
  deegree-services/deegree-webservices-handbook/src/main/asciidoc/webservices.adoc
  pom.xml
Labels: enhancement, OGCAPI

#1350 Use trimmed OGC schemas zip file (reducing size by approx. 32 MB)
  pom.xml
Labels: enhancement, dependencies
