Repository deegree/deegree3, pull requests merged in 2022-12, with the labels that each got.

#1419 Remove jettison from dependencies
  pom.xml
Labels: enhancement, dependencies

#1424 Fix conversation of foot within unit of measure handling
  deegree-core/deegree-core-style/src/main/java/org/deegree/style/utils/UomCalculator.java
Labels: bug, WMS

#1428 Speed up transcoding SVG to Image
  deegree-core/deegree-core-rendering-2d/src/main/java/org/deegree/rendering/r2d/SvgImageTranscoder.java
  deegree-core/deegree-core-rendering-2d/src/main/java/org/deegree/rendering/r2d/SvgRenderer.java
Labels: enhancement, WMS

#1414 Enable support for 4-band raster data with GdalLayer
  deegree-layers/deegree-layers-gdal/src/main/java/org/deegree/layer/persistence/gdal/GdalLayerData.java
  deegree-services/deegree-webservices-handbook/src/main/asciidoc/appendix.adoc
Labels: bug, WMS

#1421 Make last glyph of font reachable for point rendering
  deegree-core/deegree-core-rendering-2d/src/test/resources/org/deegree/rendering/r2d/similaritytests/render_scene_point.png
  deegree-core/deegree-core-rendering-2d/src/test/resources/org/deegree/rendering/r2d/similaritytests/render_scene_point.xml
  deegree-core/deegree-core-rendering-2d/src/test/resources/org/deegree/rendering/r2d/similaritytests/render_scene_strokes.png
  deegree-core/deegree-core-rendering-2d/src/test/resources/org/deegree/rendering/r2d/similaritytests/render_scene_strokes.xml
  deegree-core/deegree-core-style/src/main/java/org/deegree/style/se/parser/GraphicSymbologyParser.java
Labels: bug, WMS

#1407 Add support for rectangular (box-styled) halo
  deegree-core/deegree-core-rendering-2d/pom.xml
  deegree-core/deegree-core-rendering-2d/src/main/java/org/deegree/rendering/r2d/Java2DLabelRenderer.java
  deegree-core/deegree-core-rendering-2d/src/main/java/org/deegree/rendering/r2d/Java2DTextRenderer.java
  deegree-core/deegree-core-rendering-2d/src/test/java/org/deegree/rendering/r2d/Java2DRendererTest.java
  deegree-core/deegree-core-rendering-2d/src/test/resources/org/deegree/rendering/r2d/renderertest/textstyling2.png
  deegree-core/deegree-core-rendering-2d/src/test/resources/org/deegree/rendering/r2d/renderertest/textstylinghalo.png
  deegree-services/deegree-webservices-handbook/src/main/asciidoc/images/renderstyles_halo_regular_and_boxed.png
  deegree-services/deegree-webservices-handbook/src/main/asciidoc/renderstyles.adoc
  pom.xml
Labels: enhancement, WMS

#1439 bump dbcp2 to 2.9.0 and commons-pool2 to 2.11.1
  pom.xml
Labels: enhancement, dependencies

#1435 Fix table name in generated create index statement
  deegree-datastores/deegree-featurestores/deegree-featurestore-sql/src/main/java/org/deegree/feature/persistence/sql/ddl/PostGISDDLCreator.java
Labels: bug, tools

#1391 Allow disabling trimming of simple property values in GML reader
  deegree-core/deegree-core-base/src/main/java/org/deegree/gml/commons/AbstractGMLObjectReader.java
  deegree-services/deegree-webservices-handbook/src/main/asciidoc/appendix.adoc
Labels: enhancement
