Repository deegree/deegree3, pull requests merged in 2022-01, with the labels that each got.

#1254 Bump log4j2 to v2.17.1 to resolve CVE-2021-44832
  pom.xml
Labels: CVE, dependencies

#1237 Fix request logging
  deegree-services/deegree-services-commons/src/api/java/org/deegree/services/controller/AbstractOWS.java
  deegree-services/deegree-services-commons/src/api/java/org/deegree/services/controller/OGCFrontController.java
  deegree-services/deegree-services-commons/src/main/java/org/deegree/services/controller/utils/HttpResponseBuffer.java
  deegree-services/deegree-services-commons/src/main/java/org/deegree/services/controller/utils/LoggingHttpRequestWrapper.java
  deegree-services/deegree-services-commons/src/main/java/org/deegree/services/controller/utils/LoggingHttpResponseWrapper.java
  deegree-services/deegree-services-commons/src/main/java/org/deegree/services/controller/utils/OSAASRequestLogger.java
Labels: bug, WFS, WMS, WMTS

#1136 Fixed position of SupportedRequests in deegreeWFS configuration
  deegree-services/deegree-webservices-handbook/src/main/asciidoc/webservices.adoc
Labels: bug

#1153 Added soapUI test module deegree-integrations-tests
  deegree-tests/deegree-integration-tests/README.md
  deegree-tests/deegree-integration-tests/pom.xml
  deegree-tests/deegree-integration-tests/src/main/resources/realm.properties
  deegree-tests/deegree-integration-tests/src/test/resources/deegree-acceptance-tests-soapui-project.xml
  deegree-tests/pom.xml
Labels: enhancement, under review, CI and build
