Repository deegree/deegree3, pull requests merged in 2022-10, with the labels that each got.

#1409 Enhance image similarity test
  deegree-core/deegree-core-commons/src/main/java/org/deegree/commons/utils/test/IntegrationTestUtils.java
  deegree-core/deegree-core-rendering-2d/src/test/java/org/deegree/rendering/r2d/AbstractSimilarityTest.java
  deegree-core/deegree-core-rendering-2d/src/test/java/org/deegree/rendering/r2d/Java2DRendererTest.java
  deegree-tests/deegree-wms-remoteows-tests/src/test/java/org/deegree/services/wms/RemoteWMSIntegrationTest.java
  deegree-tests/deegree-wms-similarity-tests/src/test/java/org/deegree/services/wms/WMSSimilarityIntegrationTest.java
  deegree-tests/deegree-wms-tiling-tests/src/test/java/org/deegree/services/wms/TileLayerIntegrationTest.java
  deegree-tests/deegree-wmts-tests/src/test/java/org/deegree/services/wmts/WmtsGetTileSimilarityIT.java
Labels: enhancement, WMS, WMTS

#1388 Upgrade maven jetty plugin to 10.0.12
  deegree-tests/deegree-integration-tests/pom.xml
  deegree-tests/deegree-integration-tests/src/test/resources/deegree-acceptance-tests-soapui-project.xml
  deegree-tests/deegree-integration-tests/src/test/resources/log4j2.properties
  deegree-tests/deegree-wms-remoteows-tests/pom.xml
  deegree-tests/deegree-workspace-tests/pom.xml
  deegree-tests/pom.xml
  pom.xml
Labels: enhancement, CI and build

#1397 Dependency updates for deegree 3.4 (backport from 3.5)
  pom.xml
Labels: dependencies

#1412 Extend the serialization of SQL/MM (curved) geometries to WKT
  deegree-core/deegree-core-geometry/src/main/java/org/deegree/geometry/io/WKTWriter.java
  deegree-core/deegree-core-geometry/src/main/java/org/deegree/geometry/linearization/CurveLinearizer.java
  deegree-core/deegree-core-geometry/src/main/java/org/deegree/geometry/standard/multi/DefaultMultiCurve.java
  deegree-core/deegree-core-geometry/src/test/java/org/deegree/geometry/io/WKTWriterSqlMMTests.java
Labels: enhancement, modules
