Repository deegree/deegree3, pull requests merged in 2022-03, with the labels that each got.

#1280 Ensure that tmp files are deleted with enabled buffering in WFS and when a request is closed
  deegree-services/deegree-services-commons/src/main/java/org/deegree/services/controller/utils/HttpResponseBuffer.java
Labels: bug, WFS

#1181 Remove deegree-sqldialect-postgis dependency from deegree-featurestore-sql
  deegree-datastores/deegree-featurestores/deegree-featurestore-sql/pom.xml
  deegree-datastores/deegree-featurestores/deegree-featurestore-sql/src/main/java/org/deegree/feature/persistence/sql/ddl/DDLCreator.java
  deegree-datastores/deegree-featurestores/deegree-featurestore-sql/src/test/java/org/deegree/feature/persistence/sql/org/deegree/feature/persistence/sql/config/SQLFeatureStoreConfigWriterIT.java
Labels: enhancement, needs rebase, CI failing

#1296 Bump h2 from 1.3.171 to 2.1.210 and fix issue in creation of table LOCKS
  deegree-datastores/deegree-featurestores/deegree-featurestore-commons/src/main/java/org/deegree/feature/persistence/lock/DefaultLockManager.java
  pom.xml
Labels: bug, enhancement, dependencies

#819 Enhanced WMS GetMap request by the vendor specific parameters FILTERPROPERTY and FILTERVALUE to filter the underlying data source
  deegree-core/deegree-core-layer/src/main/java/org/deegree/layer/LayerQuery.java
  deegree-core/deegree-core-layer/src/test/java/org/deegree/layer/LayerQueryTest.java
  deegree-layers/deegree-layers-feature/pom.xml
  deegree-layers/deegree-layers-feature/src/main/java/org/deegree/layer/persistence/feature/FeatureLayer.java
  deegree-layers/deegree-layers-feature/src/main/java/org/deegree/layer/persistence/feature/FilterBuilder.java
  deegree-layers/deegree-layers-feature/src/test/java/org/deegree/layer/persistence/feature/FilterBuilderTest.java
  deegree-services/deegree-webservices-handbook/src/main/asciidoc/webservices.adoc
Labels: enhancement, ready, TMC discussion

#843 Fixing wps client bug: LiteralInputs don't have to have a DataType specified
  deegree-core/deegree-core-protocol/deegree-protocol-commons/src/main/java/org/deegree/protocol/wps/client/process/ProcessDetails.java
Labels: bug, under review

#1299 Fixed Error "Table "DBF_INDEX" already exists"
  deegree-datastores/deegree-featurestores/deegree-featurestore-shape/src/main/java/org/deegree/feature/persistence/shape/DbfIndexImporter.java
Labels: bug

#1281 Improve curve linearization
  deegree-core/deegree-core-geometry/src/main/java/org/deegree/geometry/linearization/CurveLinearizer.java
  deegree-core/deegree-core-geometry/src/test/java/org/deegree/geometry/linearization/CurveLinearizerTest.java
Labels: bug, WFS

#1286 Optimize logging for feature references to speed up batch import jobs
  deegree-core/deegree-core-base/src/main/java/org/deegree/feature/Features.java
  deegree-core/deegree-core-base/src/main/java/org/deegree/gml/reference/GmlDocumentIdContext.java
Labels: enhancement

#1289 Optimize logging of SQLFeaturestore in initialization phase
  deegree-datastores/deegree-featurestores/deegree-featurestore-sql/src/main/java/org/deegree/feature/persistence/sql/SQLFeatureStore.java
Labels: enhancement
