Repository deegree/deegree3, pull requests merged in 2022-08, with the labels that each got.

#1353 Implement PointsList#copy() and JTSPoints#copy()
  deegree-core/deegree-core-commons/src/main/java/org/deegree/commons/tom/Reference.java
  deegree-core/deegree-core-geometry/src/main/java/org/deegree/geometry/primitive/Point.java
  deegree-core/deegree-core-geometry/src/main/java/org/deegree/geometry/refs/PointReference.java
  deegree-core/deegree-core-geometry/src/main/java/org/deegree/geometry/standard/points/JTSPoints.java
  deegree-core/deegree-core-geometry/src/main/java/org/deegree/geometry/standard/points/PointsList.java
  deegree-core/deegree-core-geometry/src/main/java/org/deegree/geometry/standard/primitive/DefaultPoint.java
Labels: enhancement

#1367 Upgrade to PostGIS 2.5.1, usage of JTS WKTReader instead of PostGIS WKTReader
  deegree-core/deegree-core-geometry/src/main/java/org/deegree/geometry/GeometryFactory.java
  deegree-core/deegree-core-geometry/src/main/java/org/deegree/geometry/io/WKBReader.java
  deegree-core/deegree-core-geometry/src/main/java/org/deegree/geometry/io/WKTReader.java
  deegree-core/deegree-core-geometry/src/main/java/org/deegree/geometry/standard/AbstractDefaultGeometry.java
  deegree-core/deegree-core-geometry/src/main/java/org/deegree/geometry/utils/GeometryUtils.java
  deegree-core/deegree-core-geometry/src/test/java/org/deegree/geometry/io/WKTReaderTest.java
  pom.xml
Labels: dependencies

#1347 Ignore attribute xsi:type and log warning
  deegree-core/deegree-core-base/src/main/java/org/deegree/gml/commons/AbstractGMLObjectReader.java
Labels: bug

#1346 Fix export of returnFeatureTypes without namespace in StoredQueryDefinitionEncoder
  deegree-core/deegree-core-protocol/deegree-protocol-wfs/src/main/java/org/deegree/protocol/wfs/storedquery/xml/StoredQueryDefinition200Encoder.java
  deegree-core/deegree-core-protocol/deegree-protocol-wfs/src/test/java/org/deegree/protocol/wfs/storedquery/xml/StoredQueryDefinition200EncoderTest.java
Labels: bug
