Repository deegree/deegree3, pull requests merged in 2022-07, with the labels that each got.

#1357 Maven module deegree-webservices-tomcat-bundle removed from build
  deegree-services/deegree-webservices-handbook/src/main/asciidoc/appendix.adoc
  deegree-services/deegree-webservices-handbook/src/main/asciidoc/basics.adoc
  deegree-services/deegree-webservices-handbook/src/main/asciidoc/featurestores.adoc
  deegree-services/deegree-webservices-handbook/src/main/asciidoc/installation.adoc
  deegree-services/deegree-webservices-handbook/src/main/asciidoc/javamodules.adoc
  deegree-services/deegree-webservices-handbook/src/main/asciidoc/lightly.adoc
  deegree-services/deegree-webservices-handbook/src/main/asciidoc/webservices.adoc
  deegree-services/deegree-webservices-tomcat-bundle/pom.xml
  deegree-services/deegree-webservices-tomcat-bundle/src/main/assembly/distribution-assembly.xml
  deegree-services/pom.xml
Labels: documentation, dependencies, CI and build

#1163 Updates needed for implementation of OGC API Features Part 2 (CRS)
  deegree-datastores/deegree-featurestores/deegree-featurestore-commons/src/main/java/org/deegree/feature/persistence/FeatureStore.java
  deegree-datastores/deegree-featurestores/deegree-featurestore-memory/src/main/java/org/deegree/feature/persistence/memory/MemoryFeatureStore.java
  deegree-datastores/deegree-featurestores/deegree-featurestore-memory/src/main/java/org/deegree/feature/persistence/memory/MemoryFeatureStoreTransaction.java
  deegree-datastores/deegree-featurestores/deegree-featurestore-remotewfs/src/main/java/org/deegree/feature/persistence/remotewfs/RemoteWFSFeatureStore.java
  deegree-datastores/deegree-featurestores/deegree-featurestore-shape/src/main/java/org/deegree/feature/persistence/shape/ShapeFeatureStore.java
  deegree-datastores/deegree-featurestores/deegree-featurestore-simplesql/src/main/java/org/deegree/feature/persistence/simplesql/SimpleSQLFeatureStore.java
  deegree-datastores/deegree-featurestores/deegree-featurestore-sql/src/main/java/org/deegree/feature/persistence/sql/SQLFeatureStore.java
Labels: enhancement, OGCAPI, contributor review

#1358 Update version in documentation to 3.5
  deegree-services/deegree-webservices-handbook/src/main/asciidoc/intro.adoc
  deegree-services/deegree-webservices-handbook/src/main/asciidoc/metadatastores.adoc
  deegree-services/deegree-webservices-handbook/src/main/asciidoc/serverconnections.adoc
Labels: documentation

#1360 Ensure creation of new default points to avoid unexpected JTS Geometries
  deegree-core/deegree-core-geometry/src/main/java/org/deegree/geometry/standard/points/JTSPoints.java
Labels: bug

#1345 Fix default values of maxFeatures and featureInfoRadius
  deegree-core/deegree-core-rendering-2d/src/main/java/org/deegree/rendering/r2d/context/MapOptions.java
Labels: bug

#1359 Update contributers
  CONTRIBUTORS.md
Labels: documentation
