Repository deegree/deegree3, pull requests merged in 2022-02, with the labels that each got.

#1267 Upgrade Batik to v1.14
  deegree-core/deegree-core-style/src/main/java/org/deegree/style/utils/ShapeHelper.java
  pom.xml
Labels: CVE, dependencies

#1206 Fix Oracle 11g.R2 compability, upgrade Oracle Driver to 19.3.0.0 and remove use of profile for public available Oracle database drivers
  deegree-core/deegree-core-sqldialect/deegree-sqldialect-commons/src/main/java/org/deegree/sqldialect/AbstractSQLDialect.java
  deegree-core/deegree-core-sqldialect/deegree-sqldialect-commons/src/main/java/org/deegree/sqldialect/SQLDialect.java
  deegree-core/deegree-core-sqldialect/deegree-sqldialect-oracle/pom.xml
  deegree-core/deegree-core-sqldialect/deegree-sqldialect-oracle/src/main/java/org/deegree/sqldialect/oracle/OracleDialect.java
  deegree-core/deegree-core-sqldialect/pom.xml
  deegree-datastores/deegree-coveragestores/deegree-coveragestore-oracle-georaster/pom.xml
  deegree-datastores/deegree-featurestores/deegree-featurestore-commons/src/main/java/org/deegree/feature/persistence/FeatureStore.java
  deegree-datastores/deegree-featurestores/deegree-featurestore-commons/src/main/java/org/deegree/feature/persistence/query/Query.java
  deegree-datastores/deegree-featurestores/deegree-featurestore-memory/src/main/java/org/deegree/feature/persistence/memory/MemoryFeatureStore.java
  deegree-datastores/deegree-featurestores/deegree-featurestore-remotewfs/src/main/java/org/deegree/feature/persistence/remotewfs/RemoteWFSFeatureStore.java
  deegree-datastores/deegree-featurestores/deegree-featurestore-shape/src/main/java/org/deegree/feature/persistence/shape/ShapeFeatureStore.java
  deegree-datastores/deegree-featurestores/deegree-featurestore-simplesql/src/main/java/org/deegree/feature/persistence/simplesql/SimpleSQLFeatureStore.java
  deegree-datastores/deegree-featurestores/deegree-featurestore-sql/src/main/java/org/deegree/feature/persistence/sql/SQLFeatureStore.java
  deegree-services/deegree-services-wfs/src/main/java/org/deegree/services/wfs/format/gml/request/GmlGetFeatureHandler.java
  deegree-services/deegree-services-wfs/src/main/java/org/deegree/services/wfs/query/QueryAnalyzer.java
  pom.xml
Labels: enhancement

#1256 Fix JAI dependencies
  deegree-core/deegree-core-coverage/pom.xml
  deegree-core/deegree-core-coverage/src/main/java/org/deegree/coverage/raster/io/imageio/IIORasterDataReader.java
  deegree-core/deegree-core-coverage/src/main/java/org/deegree/coverage/raster/io/imageio/geotiff/GeoTiffIIOMetadataAdapter.java
  deegree-core/deegree-core-coverage/src/main/java/org/deegree/coverage/raster/io/imageio/geotiff/GeoTiffWriter.java
  deegree-core/deegree-core-cs/pom.xml
  deegree-core/deegree-core-metadata/src/main/java/org/deegree/metadata/DCRecord.java
  deegree-core/deegree-core-rendering-2d/pom.xml
  deegree-datastores/deegree-tilestores/deegree-tilestore-filesystem/pom.xml
  deegree-datastores/deegree-tilestores/deegree-tilestore-geotiff/pom.xml
  deegree-services/deegree-services-csw/src/main/java/org/deegree/services/csw/getrecords/Query.java
  deegree-services/deegree-services-wfs/pom.xml
  pom.xml
Labels: WMS, WMTS, dependencies

#1199 Support of CRS:84 in GdalLayer
  deegree-core/deegree-core-gdal/src/main/java/org/deegree/commons/gdal/GdalSettings.java
  deegree-layers/deegree-layers-gdal/src/main/java/org/deegree/layer/persistence/gdal/GdalLayerData.java
Labels: bug, WMS

#1275 Remove oracle profile from deegree-tools-gml and deegree-featurestore-sql
  deegree-datastores/deegree-featurestores/deegree-featurestore-sql/pom.xml
  deegree-tools/deegree-tools-gml/pom.xml
Labels: dependencies, tools
