Repository deegree/deegree3, pull requests merged in 2022-11, with the labels that each got.

#1288 Add an extension to the oracle dialect that works analog to the FeatureInspector
  deegree-core/deegree-core-sqldialect/deegree-sqldialect-oracle/src/main/java/org/deegree/sqldialect/oracle/OracleGeometryConverter.java
  deegree-core/deegree-core-sqldialect/deegree-sqldialect-oracle/src/main/java/org/deegree/sqldialect/oracle/sdo/OracleObjectTools.java
  deegree-core/deegree-core-sqldialect/deegree-sqldialect-oracle/src/main/java/org/deegree/sqldialect/oracle/sdo/SDOGeometry.java
  deegree-core/deegree-core-sqldialect/deegree-sqldialect-oracle/src/main/java/org/deegree/sqldialect/oracle/sdo/SDOGeometryConverter.java
  deegree-core/deegree-core-sqldialect/deegree-sqldialect-oracle/src/main/java/org/deegree/sqldialect/oracle/sdo/SDOInspector.java
  deegree-core/deegree-core-sqldialect/deegree-sqldialect-oracle/src/test/java/org/deegree/sqldialect/oracle/sdo/SDOGeometryConverterExampleTests.java
  deegree-core/deegree-core-sqldialect/deegree-sqldialect-oracle/src/test/java/org/deegree/sqldialect/oracle/sdo/SDOGeometryConverterTest.java
Labels: enhancement

#1400 Add FME as WPS process provider
  deegree-core/deegree-core-commons/pom.xml
  deegree-core/deegree-core-commons/src/main/java/org/deegree/commons/json/JSONAdapter.java
  deegree-core/deegree-core-commons/src/main/java/org/deegree/commons/json/JSONParsingException.java
  deegree-processproviders/deegree-processprovider-fme/pom.xml
  deegree-processproviders/deegree-processprovider-fme/src/main/java/org/deegree/services/wps/provider/fme/FMEInvocationStrategy.java
  deegree-processproviders/deegree-processprovider-fme/src/main/java/org/deegree/services/wps/provider/fme/FMEJobSubmitterInvocationStrategy.java
  deegree-processproviders/deegree-processprovider-fme/src/main/java/org/deegree/services/wps/provider/fme/FMEProcess.java
  deegree-processproviders/deegree-processprovider-fme/src/main/java/org/deegree/services/wps/provider/fme/FMEProcessMetadata.java
  deegree-processproviders/deegree-processprovider-fme/src/main/java/org/deegree/services/wps/provider/fme/FMEProcessProvider.java
  deegree-processproviders/deegree-processprovider-fme/src/main/java/org/deegree/services/wps/provider/fme/FMEProcessProviderBuilder.java
  deegree-processproviders/deegree-processprovider-fme/src/main/java/org/deegree/services/wps/provider/fme/FMEProcessProviderProvider.java
  deegree-processproviders/deegree-processprovider-fme/src/main/java/org/deegree/services/wps/provider/fme/FMEProcesslet.java
  deegree-processproviders/deegree-processprovider-fme/src/main/resources/META-INF/console/resourceprovider/org.deegree.services.wps.provider.fme.FMEProcessProviderProvider
  deegree-processproviders/deegree-processprovider-fme/src/main/resources/META-INF/schemas/processes/fme/example.xml
  deegree-processproviders/deegree-processprovider-fme/src/main/resources/META-INF/schemas/processes/fme/fme.xsd
  deegree-processproviders/deegree-processprovider-fme/src/main/resources/META-INF/services/org.deegree.services.wps.provider.ProcessProviderProvider
  deegree-processproviders/pom.xml
  deegree-services/deegree-services-wps/src/main/java/org/deegree/services/wps/WPService.java
  deegree-services/deegree-webservices-handbook/src/main/asciidoc/processproviders.adoc
  deegree-services/deegree-webservices/pom.xml
  deegree-workspaces/deegree-workspace-fme/pom.xml
  deegree-workspaces/deegree-workspace-fme/src/assembly/assembly.xml
  deegree-workspaces/deegree-workspace-fme/src/main/resources/processes/fmeServer.xml
  deegree-workspaces/deegree-workspace-fme/src/main/resources/services/wps.xml
  deegree-workspaces/pom.xml
  pom.xml
Labels: enhancement, WPS, workspace

#1420 Extend tests in deegree-core-rendering-2d with similarity unit tests
  deegree-core/deegree-core-rendering-2d/src/test/java/org/deegree/rendering/r2d/RenderedStyleImageSimilarityTest.java
  deegree-core/deegree-core-rendering-2d/src/test/resources/org/deegree/rendering/r2d/similaritytests/TestSymbol.ttf
  deegree-core/deegree-core-rendering-2d/src/test/resources/org/deegree/rendering/r2d/similaritytests/elipse.svg
  deegree-core/deegree-core-rendering-2d/src/test/resources/org/deegree/rendering/r2d/similaritytests/randombg.png
  deegree-core/deegree-core-rendering-2d/src/test/resources/org/deegree/rendering/r2d/similaritytests/render_scene_fill.gml
  deegree-core/deegree-core-rendering-2d/src/test/resources/org/deegree/rendering/r2d/similaritytests/render_scene_fill.png
  deegree-core/deegree-core-rendering-2d/src/test/resources/org/deegree/rendering/r2d/similaritytests/render_scene_fill.xml
  deegree-core/deegree-core-rendering-2d/src/test/resources/org/deegree/rendering/r2d/similaritytests/render_scene_fill_wkn.gml
  deegree-core/deegree-core-rendering-2d/src/test/resources/org/deegree/rendering/r2d/similaritytests/render_scene_fill_wkn.png
  deegree-core/deegree-core-rendering-2d/src/test/resources/org/deegree/rendering/r2d/similaritytests/render_scene_fill_wkn.xml
  deegree-core/deegree-core-rendering-2d/src/test/resources/org/deegree/rendering/r2d/similaritytests/render_scene_point.gml
  deegree-core/deegree-core-rendering-2d/src/test/resources/org/deegree/rendering/r2d/similaritytests/render_scene_point.png
  deegree-core/deegree-core-rendering-2d/src/test/resources/org/deegree/rendering/r2d/similaritytests/render_scene_point.xml
  deegree-core/deegree-core-rendering-2d/src/test/resources/org/deegree/rendering/r2d/similaritytests/render_scene_strokes.gml
  deegree-core/deegree-core-rendering-2d/src/test/resources/org/deegree/rendering/r2d/similaritytests/render_scene_strokes.png
  deegree-core/deegree-core-rendering-2d/src/test/resources/org/deegree/rendering/r2d/similaritytests/render_scene_strokes.xml
  deegree-core/deegree-core-rendering-2d/src/test/resources/org/deegree/rendering/r2d/similaritytests/sample_w_border.svg
  deegree-core/deegree-core-rendering-2d/src/test/resources/org/deegree/rendering/r2d/similaritytests/sample_wo_border.svg
  deegree-core/deegree-core-rendering-2d/src/test/resources/org/deegree/rendering/r2d/similaritytests/sample_wo_border_and_line.svg
Labels: enhancement, WMS

#1423 Optimization of vendor-specific rendering of a graphic on a line
  deegree-core/deegree-core-rendering-2d/src/main/java/org/deegree/rendering/r2d/Java2DStrokeRenderer.java
  deegree-core/deegree-core-rendering-2d/src/main/java/org/deegree/rendering/r2d/RendererContext.java
  deegree-core/deegree-core-rendering-2d/src/main/java/org/deegree/rendering/r2d/strokes/ShapeStroke.java
  deegree-core/deegree-core-rendering-2d/src/test/resources/org/deegree/rendering/r2d/similaritytests/render_scene_graphicstroke.gml
  deegree-core/deegree-core-rendering-2d/src/test/resources/org/deegree/rendering/r2d/similaritytests/render_scene_graphicstroke.png
  deegree-core/deegree-core-rendering-2d/src/test/resources/org/deegree/rendering/r2d/similaritytests/render_scene_graphicstroke.xml
  deegree-core/deegree-core-rendering-2d/src/test/resources/org/deegree/rendering/r2d/similaritytests/render_scene_strokes.gml
  deegree-core/deegree-core-rendering-2d/src/test/resources/org/deegree/rendering/r2d/similaritytests/render_scene_strokes.png
  deegree-core/deegree-core-rendering-2d/src/test/resources/org/deegree/rendering/r2d/similaritytests/render_scene_strokes.xml
  deegree-core/deegree-core-style/src/main/java/org/deegree/style/se/parser/StrokeSymbologyParser.java
  deegree-core/deegree-core-style/src/main/java/org/deegree/style/styling/components/Fill.java
  deegree-core/deegree-core-style/src/main/java/org/deegree/style/styling/components/Stroke.java
  deegree-services/deegree-webservices-handbook/src/main/asciidoc/appendix.adoc
  deegree-services/deegree-webservices-handbook/src/main/asciidoc/renderstyles.adoc
Labels: enhancement, WMS

#1429 Update Oracle driver to 19.9.0.0
  deegree-services/deegree-webservices-handbook/src/main/asciidoc/serverconnections.adoc
  pom.xml
Labels: bug, dependencies

#1090 Fixed html.gfi to avoid same gml id for all features
  deegree-core/deegree-core-featureinfo/pom.xml
  deegree-core/deegree-core-featureinfo/src/main/resources/org/deegree/featureinfo/html.gfi
  deegree-core/deegree-core-featureinfo/src/test/java/org/deegree/featureinfo/serializing/TemplateFeatureInfoSerializerTest.java
  deegree-core/deegree-core-featureinfo/src/test/resources/org/deegree/featureinfo/serializing/featurecollection.gml
  deegree-tests/deegree-csw-bkg/src/main/webapp/WEB-INF/workspace/jdbc/conn1.xml
  deegree-tests/deegree-csw-bkg/src/main/workspace/jdbc/conn1.xml
  deegree-tests/deegree-wmts-tests/src/test/resources/getFeatureInfo/cached_gfi.html
  deegree-tests/deegree-wmts-tests/src/test/resources/getFeatureInfo/remotewmsfi.html
Labels: bug, WMS

#1395 Make decimal places of numeric values in GetFeatureInfo for cover configurable
  deegree-core/deegree-core-layer/src/main/java/org/deegree/layer/config/ConfigUtils.java
  deegree-core/deegree-core-layer/src/main/resources/META-INF/schemas/layers/base/base.xsd
  deegree-core/deegree-core-rendering-2d/src/main/java/org/deegree/rendering/r2d/context/MapOptions.java
  deegree-layers/deegree-layers-coverage/src/main/java/org/deegree/layer/persistence/coverage/CoverageFeatureInfoHandler.java
  deegree-layers/deegree-layers-coverage/src/main/java/org/deegree/layer/persistence/coverage/CoverageLayer.java
  deegree-layers/deegree-layers-coverage/src/main/java/org/deegree/layer/persistence/coverage/CoverageLayerData.java
  deegree-services/deegree-services-wms/src/main/java/org/deegree/services/wms/controller/capabilities/theme/LayerMetadataMerger.java
  deegree-services/deegree-services-wms/src/test/java/org/deegree/services/wms/controller/capabilities/theme/LayerMetadataMergerTest.java
  deegree-services/deegree-webservices-handbook/src/main/asciidoc/layers.adoc
Labels: enhancement, WMS, schema change

#1402 Prevent serialization of exceptions with "null" message
  deegree-services/deegree-services-csw/src/main/java/org/deegree/services/csw/CswExceptionReportSerializer.java
  deegree-services/deegree-services-wcs/src/main/java/org/deegree/services/wcs/WCS100ServiceExceptionReportSerializer.java
  deegree-services/deegree-services-wms/src/main/java/org/deegree/services/wms/controller/WMS111ExceptionReportSerializer.java
Labels: bug, WMS, CSW, WCS

#1406 Adds endpoint to REST API to list available fonts on the server
  deegree-services/deegree-services-config/src/main/java/org/deegree/services/config/actions/ListFonts.java
  deegree-services/deegree-services-config/src/main/java/org/deegree/services/config/servlet/ConfigServlet.java
  deegree-services/deegree-webservices-handbook/src/main/asciidoc/restapi.adoc
Labels: enhancement, rest-api

#1403 Fix NPE in console if resources are inside subfolders
  deegree-core/deegree-core-workspace/src/main/java/org/deegree/workspace/standard/DefaultResourceLocation.java
  deegree-core/deegree-core-workspace/src/test/java/org/deegree/workspace/standard/DefaultResourceLocationTest.java
Labels: bug, console

#1425 Update the documentation of deegree
  deegree-services/deegree-webservices-handbook/src/main/asciidoc/renderstyles.adoc
  deegree-services/deegree-webservices-handbook/src/main/asciidoc/webservices.adoc
Labels: documentation

#1427 Extending the SLD/SE rendering capabilities of Mark for symbols based on Well Known Text (WKT) geometries
  deegree-core/deegree-core-geometry/src/main/java/org/deegree/geometry/io/EWKTReader.java
  deegree-core/deegree-core-geometry/src/test/java/org/deegree/geometry/io/EWKTReaderWKTtoGeometryTests.java
  deegree-core/deegree-core-geometry/src/test/java/org/deegree/geometry/io/EWKTReaderWKTtoJTSGeometryTests.java
  deegree-core/deegree-core-geometry/src/test/java/org/deegree/geometry/io/EWKTReaderWKTtoWKTTests.java
  deegree-core/deegree-core-rendering-2d/src/test/resources/org/deegree/rendering/r2d/similaritytests/point_wellknownname_wkt.gml
  deegree-core/deegree-core-rendering-2d/src/test/resources/org/deegree/rendering/r2d/similaritytests/point_wellknownname_wkt.png
  deegree-core/deegree-core-rendering-2d/src/test/resources/org/deegree/rendering/r2d/similaritytests/point_wellknownname_wkt.xml
  deegree-core/deegree-core-style/src/main/java/org/deegree/style/styling/wkn/WKTLinearizeLoader.java
  deegree-core/deegree-core-style/src/main/java/org/deegree/style/styling/wkn/WKTLoader.java
  deegree-core/deegree-core-style/src/main/java/org/deegree/style/styling/wkn/shape/AbstractShapeConverter.java
  deegree-core/deegree-core-style/src/main/java/org/deegree/style/styling/wkn/shape/ShapeConverterArc.java
  deegree-core/deegree-core-style/src/main/java/org/deegree/style/styling/wkn/shape/ShapeConverterLinearize.java
  deegree-core/deegree-core-style/src/main/resources/META-INF/services/org.deegree.style.styling.mark.WellKnownNameLoader
  deegree-services/deegree-webservices-handbook/src/main/asciidoc/images/se_wkn_example/wkt_custom_form.png
  deegree-services/deegree-webservices-handbook/src/main/asciidoc/images/se_wkn_example/wkt_rhombus.png
  deegree-services/deegree-webservices-handbook/src/main/asciidoc/renderstyles.adoc
Labels: enhancement, WMS
