Repository deegree/deegree3, pull requests merged in 2022-09, with the labels that each got.

#1379 Upgrades axiom from 1.2.15 to 1.2.22
  deegree-services/deegree-services-commons/pom.xml
  deegree-services/deegree-services-commons/src/api/java/org/deegree/services/controller/OGCFrontController.java
  deegree-services/deegree-services-commons/src/test/java/org/deegree/services/controller/exception/serializer/SOAPExceptionSerializerTest.java
  pom.xml
Labels: enhancement, dependencies

#1373 Bump Mockito from 2.28.2 to 3.12.4
  pom.xml
Labels: enhancement, dependencies, CI and build

#1372 Upgrades maven surefire, failsafe, compiler, jaxb2 and jar plugins
  pom.xml
Labels: enhancement, CI and build

#1371 Upgrades maven enforcer plugin and extra rules
  pom.xml
Labels: enhancement, CI and build

#1121 Add support for ObjectPropertyType in GMLAppSchema
  deegree-core/deegree-core-base/src/main/java/org/deegree/gml/schema/GMLAppSchemaWriter.java
Labels: enhancement

#1135 fix: don't write attributes w/ unbound namespace prefix
  deegree-core/deegree-core-base/src/main/java/org/deegree/gml/feature/GMLFeatureWriter.java
  deegree-core/deegree-core-commons/src/main/java/org/deegree/commons/xml/stax/StAXExportingHelper.java
Labels: bug, WFS

#1188 Write nil and nilReason with namespaces to avoid invalid XML
  deegree-core/deegree-core-base/src/main/java/org/deegree/gml/feature/GMLFeatureWriter.java
Labels: bug, WFS, WMS

#1191 Fix GetFeatureInfo with non standard PIXELSIZE/DPI
  deegree-core/deegree-core-protocol/deegree-protocol-wms/src/main/java/org/deegree/protocol/wms/ops/GetFeatureInfo.java
  deegree-core/deegree-core-protocol/deegree-protocol-wms/src/main/java/org/deegree/protocol/wms/ops/GetMap.java
  deegree-core/deegree-core-protocol/deegree-protocol-wms/src/main/java/org/deegree/protocol/wms/ops/RequestBase.java
  deegree-services/deegree-services-wms/src/main/java/org/deegree/services/wms/MapService.java
  deegree-services/deegree-services-wms/src/main/java/org/deegree/services/wms/controller/WMSController.java
  deegree-tests/deegree-wms-similarity-tests/src/test/java/org/deegree/services/wms/GetFeatureInfoIntegrationTest.java
Labels: bug, WMS

#1384 Fix rendering of symbolizer with external SVG graphics
  deegree-core/deegree-core-style/pom.xml
Labels: bug, WMS

#1381 Fix background color issues with no-data sections in gdal tiles [3.5]
  deegree-core/deegree-core-gdal/src/main/java/org/deegree/commons/gdal/GdalDataset.java
Labels: bug, WMS, WMTS

#1382 Fix background color issues with no-data sections in gdal tiles [3.4]
  deegree-core/deegree-core-gdal/src/main/java/org/deegree/commons/gdal/GdalDataset.java
Labels: bug, WMS, WMTS

#1037 Enhance GFI templating mechanism to convert xlink:href attribute to link
  deegree-core/deegree-core-featureinfo/src/main/java/org/deegree/featureinfo/templating/lang/Link.java
Labels: enhancement, WMS

#1038 Fix AbstractWhereBuilder for Oracle DB datasources
  deegree-core/deegree-core-sqldialect/deegree-sqldialect-commons/src/main/java/org/deegree/sqldialect/filter/AbstractWhereBuilder.java
  deegree-core/deegree-core-sqldialect/deegree-sqldialect-oracle/src/main/java/org/deegree/sqldialect/oracle/OracleWhereBuilder.java
  deegree-core/deegree-core-sqldialect/deegree-sqldialect-postgis/src/main/java/org/deegree/sqldialect/postgis/PostGISWhereBuilder.java
Labels: bug

#1190 Fix rasterdata offsets
  deegree-core/deegree-core-coverage/src/main/java/org/deegree/coverage/persistence/pyramid/PyramidCoverageBuilder.java
  deegree-core/deegree-core-coverage/src/main/resources/META-INF/schemas/datasource/coverage/raster/pyramid.xsd
  deegree-services/deegree-webservices-handbook/src/main/asciidoc/coveragestores.adoc
Labels: bug, WMS

#1385 Use XMLUnit instead of byte comparison
  deegree-core/deegree-core-base/src/test/java/org/deegree/gml/geometry/GML3GeometryWriterTest.java
  deegree-core/deegree-core-metadata/pom.xml
  deegree-core/deegree-core-metadata/src/test/java/org/deegree/metadata/iso/ISORecordTest.java
  deegree-core/deegree-core-protocol/deegree-protocol-commons/pom.xml
  deegree-core/deegree-core-protocol/deegree-protocol-commons/src/test/java/org/deegree/protocol/ows/http/OwsHttpResponseTest.java
Labels: enhancement, tests

#1392 Unification of tunable parameter usage and their documentation
  deegree-core/deegree-core-commons/src/main/java/org/deegree/commons/utils/TunableParameter.java
  deegree-core/deegree-core-coverage/src/main/java/org/deegree/coverage/raster/cache/RasterCache.java
  deegree-core/deegree-core-coverage/src/main/java/org/deegree/coverage/raster/io/imageio/IIORasterDataReader.java
  deegree-core/deegree-core-coverage/src/test/java/org/deegree/coverage/raster/cache/TestRasterCache.java
  deegree-services/deegree-webservices-handbook/src/main/asciidoc/appendix.adoc
Labels: enhancement

#1294 Extend command line options for the loader tool
  deegree-services/deegree-webservices-handbook/src/main/asciidoc/cli-utility.adoc
  deegree-tools/deegree-tools-gml/src/main/java/org/deegree/tools/featurestoresql/loader/GmlLoaderConfiguration.java
  deegree-tools/deegree-tools-gml/src/main/java/org/deegree/tools/featurestoresql/loader/GmlLoaderHelpUsage.java
Labels: enhancement, tools
