Repository deegree/deegree3, pull requests merged in 2023-01, with the labels that each got.

#1443 Enhanced support of GML 3.2. geometries
  deegree-core/deegree-core-base/src/main/java/org/deegree/gml/geometry/GML3GeometryReader.java
  deegree-core/deegree-core-base/src/test/java/org/deegree/gml/geometry/GML3GeometryReaderTest.java
  deegree-core/deegree-core-base/src/test/resources/org/deegree/gml/misc/geometry/RingWithLinearRing.gml
  deegree-core/deegree-core-base/src/test/resources/org/deegree/gml/misc/geometry/RingWithRing.gml
  deegree-core/deegree-core-geometry/src/main/java/org/deegree/geometry/primitive/Curve.java
Labels: enhancement, WFS

#1442 Enhanced configuration to hide version reference in header
  deegree-services/deegree-services-commons/src/api/java/org/deegree/services/controller/OGCFrontController.java
  deegree-services/deegree-services-commons/src/main/resources/META-INF/schemas/services/controller/controller.xsd
  deegree-services/deegree-webservices-handbook/src/main/asciidoc/webservices.adoc
Labels: enhancement, WFS, WMS, CSW, WCS, WMTS, schema change

#1444 Upgrade JSF Primefaces to v12.0
  deegree-services/deegree-webservices/pom.xml
Labels: enhancement, console, dependencies

#1441 Upgrade ehcache to version 3.10.8
  deegree-core/deegree-core-coverage/pom.xml
  deegree-core/deegree-core-coverage/src/main/java/org/deegree/coverage/raster/data/container/CachedRasterDataContainer.java
  deegree-core/deegree-core-coverage/src/main/java/org/deegree/coverage/raster/data/container/StatisticsRetrieval.java
  deegree-datastores/deegree-tilestores/deegree-tilestore-cache/pom.xml
  deegree-datastores/deegree-tilestores/deegree-tilestore-cache/src/main/java/org/deegree/tile/persistence/cache/CachedTile.java
  deegree-datastores/deegree-tilestores/deegree-tilestore-cache/src/main/java/org/deegree/tile/persistence/cache/CachingTileMatrix.java
  deegree-datastores/deegree-tilestores/deegree-tilestore-cache/src/main/java/org/deegree/tile/persistence/cache/CachingTileStore.java
  deegree-datastores/deegree-tilestores/deegree-tilestore-cache/src/main/java/org/deegree/tile/persistence/cache/CachingTileStoreBuilder.java
  deegree-services/deegree-webservices-handbook/src/main/asciidoc/webservices.adoc
  deegree-tests/deegree-wmts-tests/src/main/webapp/WEB-INF/workspace/ehcache.xml
  deegree-tests/deegree-wmts-tests/src/main/webapp/WEB-INF/workspace/ehcache_remotewms.xml
  pom.xml
Labels: enhancement, WMTS, dependencies

#1447 Reworked profiles section for building deegree-webservices WAR file
  deegree-services/deegree-webservices/pom.xml
Labels: enhancement, CI and build, modules

#1454 Add option to skip reference check in GmlLoader tool
  deegree-services/deegree-webservices-handbook/src/main/asciidoc/cli-utility.adoc
  deegree-tools/deegree-tools-gml/src/main/java/org/deegree/tools/featurestoresql/loader/GmlLoaderConfiguration.java
  deegree-tools/deegree-tools-gml/src/main/java/org/deegree/tools/featurestoresql/loader/GmlLoaderHelpUsage.java
  deegree-tools/deegree-tools-gml/src/main/java/org/deegree/tools/featurestoresql/loader/TransactionHandler.java
Labels: enhancement, tools

#1460 Upgrade of JAXB implementation to v2.3.7
  deegree-tools/deegree-tools-gml/pom.xml
  pom.xml
Labels: dependencies

#1459 Fix for dependency conflicts introduced with ehcache 3.x upgrade (PR #1441)
  pom.xml
Labels: dependencies, CI and build

#1462 Upgrade of json-path to 2.7.0
  pom.xml
Labels: dependencies
