Repository deegree/deegree3, pull requests merged in 2023-11, with the labels that each got.

#1586 Remove netty dependency
  pom.xml
Labels: dependencies

#1590 Upgrade Primefaces to latest bugfix version 13.0.2
  deegree-services/deegree-webservices/pom.xml
Labels: dependencies

#1562 workaround for transformation from epsg:3857 with wrong results
  deegree-core/deegree-core-cs/src/main/java/org/deegree/cs/transformations/TransformationFactory.java
  deegree-core/deegree-core-cs/src/test/java/org/deegree/cs/transformations/Epsg3857TransformationTest.java
Labels: bug

#1453 Add new integration test for the deegree version response header default configuration
  deegree-tests/deegree-integration-tests/README.md
  deegree-tests/deegree-integration-tests/src/test/resources/deegree-acceptance-tests-soapui-project.xml
Labels: enhancement, CI and build, tests

#1589 Support combination of parameter 'skipReferenceCheck=true' and 'dryRun=true' for the GmlLoader
  deegree-tools/deegree-tools-gml/src/main/java/org/deegree/tools/featurestoresql/loader/DryRunReferenceCheck.java
  deegree-tools/deegree-tools-gml/src/main/java/org/deegree/tools/featurestoresql/loader/GmlLoaderConfiguration.java
  deegree-tools/deegree-tools-gml/src/main/java/org/deegree/tools/featurestoresql/loader/ReferenceCheckListener.java
  deegree-tools/deegree-tools-gml/src/main/java/org/deegree/tools/featurestoresql/loader/TransactionHandler.java
Labels: enhancement, tools

#1591 Remove reference to 3.4 from README.md
  README.md
Labels: website, documentation

#1452 Enforce UTF-8 as platform encoding in unit tests
  pom.xml
Labels: under review

#1598 Fix documentation for SqlFeatureStoreConfigCreator options
  deegree-services/deegree-webservices-handbook/src/main/asciidoc/cli-utility.adoc
Labels: documentation

#1593 Update README.md to fix broken link
  README.md
Labels: website, documentation

#1604 Update commons-codec to version 1.16.0 and remove redundant groupIds
  deegree-datastores/deegree-tilestores/deegree-tilestore-gdal/pom.xml
  deegree-tools/deegree-tools-gml/pom.xml
  pom.xml
  uncoupled/orphaned-after-3.2/pom.xml
Labels: dependencies

#1602 Upgrade of Maven plugins
  pom.xml
Labels: dependencies

#1601 Added srid in created SQL for blob mode and PostgreSQL
  deegree-datastores/deegree-featurestores/deegree-featurestore-sql/src/main/java/org/deegree/feature/persistence/sql/ddl/PostGISDDLCreator.java
Labels: core

#1600 Updating security policy
  SECURITY.md
Labels: TMC discussion, website, documentation

#1549 Re-activate GitHub actions
  .github/workflows/maven.yml
Labels: enhancement, TMC discussion, CI and build
