Repository deegree/deegree3, pull requests merged in 2023-05, with the labels that each got.

#1493 Fix example locations for deegree administration
  deegree-datastores/deegree-mdstores/deegree-mdstore-iso/src/main/resources/META-INF/schemas/datasource/metadata/iso19115/example.xml
  deegree-datastores/deegree-tilestores/deegree-tilestore-merge/src/main/resources/META-INF/schemas/datasource/tile/merge/example.xml
  deegree-layers/deegree-layers-gdal/src/main/resources/META-INF/schemas/layers/gdal/example.xml
  deegree-processproviders/deegree-processprovider-fme/src/main/resources/META-INF/console/resourceprovider/org.deegree.services.wps.provider.fme.FMEProcessProviderProvider
  deegree-services/deegree-webservices/src/main/resources/META-INF/console/resourceprovider/org.deegree.layer.persistence.coverage.CoverageLayerStoreProvider
  deegree-services/deegree-webservices/src/main/resources/META-INF/console/resourceprovider/org.deegree.layer.persistence.tile.TileLayerStoreProvider
  deegree-services/deegree-webservices/src/main/resources/META-INF/console/resourceprovider/org.deegree.metadata.iso.persistence.ISOMetadataStoreProvider
  deegree-themes/deegree-themes-remotewms/src/main/resources/META-INF/schemas/themes/remotewms/example.xml
Labels: bug, console

#1488 Upgraded maven surefire, failsafe, enforcer and jetty plugins to latest versions
  deegree-tests/deegree-integration-tests/pom.xml
  pom.xml
Labels: dependencies, CI and build

#1472 Update the schemaLocation URL in config templates to be valid
  deegree-core/deegree-connectionprovider-datasource/src/main/resources/META-INF/schemas/connectionprovider/datasource/example_dbcp_mssql.xml
  deegree-core/deegree-connectionprovider-datasource/src/main/resources/META-INF/schemas/connectionprovider/datasource/example_dbcp_oracle.xml
  deegree-core/deegree-connectionprovider-datasource/src/main/resources/META-INF/schemas/connectionprovider/datasource/example_dbcp_postgres.xml
  deegree-core/deegree-connectionprovider-datasource/src/main/resources/META-INF/schemas/connectionprovider/datasource/example_jndi.xml
  deegree-core/deegree-connectionprovider-datasource/src/main/resources/META-INF/schemas/connectionprovider/datasource/example_ucp.xml
  deegree-services/deegree-webservices-handbook/src/main/asciidoc/metadatastores.adoc
  deegree-services/deegree-webservices-handbook/src/main/asciidoc/renderstyles.adoc
  deegree-services/deegree-webservices-handbook/src/main/asciidoc/serverconnections.adoc
Labels: bug, website, documentation, console

#1497 Update and fix links in the documentation
  deegree-services/deegree-webservices-handbook/src/main/asciidoc/basics.adoc
  deegree-services/deegree-webservices-handbook/src/main/asciidoc/crs.adoc
  deegree-services/deegree-webservices-handbook/src/main/asciidoc/featurestores.adoc
  deegree-services/deegree-webservices-handbook/src/main/asciidoc/gdal.adoc
  deegree-services/deegree-webservices-handbook/src/main/asciidoc/installation.adoc
  deegree-services/deegree-webservices-handbook/src/main/asciidoc/intro.adoc
  deegree-services/deegree-webservices-handbook/src/main/asciidoc/javamodules.adoc
  deegree-services/deegree-webservices-handbook/src/main/asciidoc/lightly.adoc
  deegree-services/deegree-webservices-handbook/src/main/asciidoc/metadatastores.adoc
  deegree-services/deegree-webservices-handbook/src/main/asciidoc/processproviders.adoc
  deegree-services/deegree-webservices-handbook/src/main/asciidoc/renderstyles.adoc
  deegree-services/deegree-webservices-handbook/src/main/asciidoc/serverconnections.adoc
  deegree-services/deegree-webservices-handbook/src/main/asciidoc/tilestores.adoc
  deegree-services/deegree-webservices-handbook/src/main/asciidoc/webservices.adoc
Labels: enhancement, documentation

#1479 Enhanced configuration of RemoteWMS Layer by legend graphics
  deegree-core/deegree-core-protocol/deegree-protocol-wms/src/main/java/org/deegree/protocol/wms/client/WMSCapabilitiesAdapter.java
  deegree-layers/deegree-layers-remotewms/src/main/java/org/deegree/layer/persistence/remotewms/RemoteWmsLayerBuilder.java
  deegree-layers/deegree-layers-remotewms/src/main/resources/META-INF/schemas/layers/remotewms/remotewms.xsd
  deegree-services/deegree-webservices-handbook/src/main/asciidoc/layers.adoc
Labels: enhancement, WMS

#1478 Add configuration of legends for group layer
  deegree-core/deegree-core-theme/src/main/java/org/deegree/theme/persistence/standard/StandardThemeBuilder.java
  deegree-core/deegree-core-theme/src/main/resources/META-INF/schemas/themes/themes.xsd
  deegree-services/deegree-webservices-handbook/src/main/asciidoc/themes.adoc
Labels: enhancement, WMS

#1498 Added ApiKey/Token authentication
  deegree-services/deegree-services-config/src/main/java/org/deegree/services/config/ApiKey.java
  deegree-services/deegree-services-config/src/main/java/org/deegree/services/config/servlet/ConfigServlet.java
  deegree-services/deegree-webservices-handbook/src/main/asciidoc/appendix.adoc
  deegree-services/deegree-webservices-handbook/src/main/asciidoc/basics.adoc
  deegree-services/deegree-webservices-handbook/src/main/asciidoc/restapi.adoc
  deegree-services/deegree-webservices/src/main/webapp/WEB-INF/web.xml
  deegree-tests/deegree-integration-tests/src/main/webapp/WEB-INF/workspaces/config.apikey
  deegree-tests/deegree-testservice/src/main/webapp/WEB-INF/web.xml
  deegree-tests/deegree-workspace-tests/src/main/.gitignore
  deegree-tests/deegree-workspace-tests/src/main/webapp/WEB-INF/workspaces/config.apikey
Labels: documentation, OGCAPI, rest-api

#1467 Apply count and startindex to queries without SORTBY/FILTER in blob mode
  deegree-datastores/deegree-featurestores/deegree-featurestore-sql/src/main/java/org/deegree/feature/persistence/sql/SQLFeatureStore.java
Labels: bug, WFS

#1499 Fix invalid SQL when OrderBy is configured in SQLFeatureStore
  deegree-core/deegree-core-sqldialect/deegree-sqldialect-commons/src/main/java/org/deegree/sqldialect/SortCriterion.java
  deegree-core/deegree-core-sqldialect/deegree-sqldialect-commons/src/main/java/org/deegree/sqldialect/filter/AbstractWhereBuilder.java
  deegree-datastores/deegree-featurestores/deegree-featurestore-sql/src/main/java/org/deegree/feature/persistence/sql/config/AbstractMappedSchemaBuilder.java
  deegree-datastores/deegree-featurestores/deegree-featurestore-sql/src/main/java/org/deegree/feature/persistence/sql/config/MappedSchemaBuilderGML.java
  deegree-datastores/deegree-featurestores/deegree-featurestore-sql/src/main/java/org/deegree/feature/persistence/sql/config/MappedSchemaBuilderTable.java
Labels: bug, WFS

#1505 Replaced org:deegree:junidecode:0.2 with net.gcardone.junidecode:junidecode.0.4.1
  deegree-datastores/deegree-featurestores/deegree-featurestore-sql/pom.xml
  deegree-datastores/deegree-featurestores/deegree-featurestore-sql/src/main/java/org/deegree/feature/persistence/sql/mapper/MappingContextManager.java
  pom.xml
Labels: dependencies

#1448 Improved documentation how to configure deegree for offline startup with schema-driven feature stores
  deegree-services/deegree-webservices-handbook/src/main/asciidoc/featurestores.adoc
  pom.xml
Labels: enhancement, documentation

#1506 Update database information in documentation and include sqldialect for oracle and mssql in regular webservices
  deegree-core/deegree-core-sqldialect/deegree-sqldialect-mssql/pom.xml
  deegree-core/deegree-core-sqldialect/pom.xml
  deegree-datastores/deegree-featurestores/deegree-featurestore-sql/pom.xml
  deegree-services/deegree-webservices-handbook/src/main/asciidoc/javamodules.adoc
  deegree-services/deegree-webservices-handbook/src/main/asciidoc/serverconnections.adoc
  deegree-services/deegree-webservices/pom.xml
  pom.xml
Labels: documentation, dependencies

#1508 Update capabilities and metadata template examples with new information
  deegree-core/deegree-core-protocol/deegree-protocol-commons/src/test/resources/org/deegree/protocol/ows/http/scenario1.xml
  deegree-core/deegree-core-protocol/deegree-protocol-wms/src/test/java/org/deegree/protocol/wms/client/WMSCapabilitiesAdapterTest.java
  deegree-core/deegree-core-protocol/deegree-protocol-wms/src/test/resources/org/deegree/protocol/wms/client/wms111-inspire-capabilities.xml
  deegree-core/deegree-core-protocol/deegree-protocol-wms/src/test/resources/org/deegree/protocol/wms/client/wms111.xml
  deegree-core/deegree-core-protocol/deegree-protocol-wms/src/test/resources/org/deegree/protocol/wms/client/wms130-capabilities-getmap-endpoint-extra-params-no-amp-at-end.xml
  deegree-core/deegree-core-protocol/deegree-protocol-wms/src/test/resources/org/deegree/protocol/wms/client/wms130-capabilities-getmap-endpoint-extraparams-amp.xml
  deegree-core/deegree-core-protocol/deegree-protocol-wms/src/test/resources/org/deegree/protocol/wms/client/wms130-capabilities-getmap-endpoint-noquestionmark.xml
  deegree-core/deegree-core-protocol/deegree-protocol-wms/src/test/resources/org/deegree/protocol/wms/client/wms130-capabilities.xml
  deegree-core/deegree-core-protocol/deegree-protocol-wms/src/test/resources/org/deegree/protocol/wms/client/wms130-inspire-capabilities.xml
  deegree-core/deegree-core-protocol/deegree-protocol-wms/src/test/resources/org/deegree/protocol/wms/client/wms130.xml
  deegree-core/deegree-core-protocol/deegree-protocol-wmts/src/test/resources/org/deegree/protocol/wmts/client/wmts100_capabilities_example.xml
  deegree-core/deegree-core-remoteows/deegree-remoteows-wmts/src/test/resources/org/deegree/remoteows/wmts/capabilities_example.xml
  deegree-processproviders/deegree-processprovider-example/src/main/webapp/WEB-INF/workspace/services/metadata.xml
  deegree-services/deegree-services-wms/src/test/java/org/deegree/services/wms/controller/capabilities/serialize/XsltCapabilitiesSerializerTest.java
  deegree-services/deegree-services-wms/src/test/resources/org/deegree/services/wms/controller/capabilities/serialize/wmsCapabilities_130.xml
  deegree-services/deegree-services-wps/src/test/resources/org/deegree/services/wps/services_metadata.xml
  deegree-tests/deegree-wms-remoteows-tests/src/main/webapp/WEB-INF/workspace/datasources/remoteows/capabilities.xml
  deegree-tests/deegree-wms-remoteows-tests/src/main/webapp/WEB-INF/workspace/services/metadata.xml
  deegree-tests/deegree-wms-similarity-tests/src/main/webapp/WEB-INF/workspace/services/metadata.xml
  deegree-tests/deegree-wmts-tests/src/main/webapp/WEB-INF/workspace/faultycaps.xml
  deegree-workspaces/deegree-workspace-aixm/src/main/resources/services/metadata.xml
  deegree-workspaces/deegree-workspace-compliance-tests/src/main/resources/services/metadata.xml
  deegree-workspaces/deegree-workspace-csw/src/main/resources/services/metadata.xml
  deegree-workspaces/deegree-workspace-geosciml/src/main/resources/services/metadata.xml
  deegree-workspaces/deegree-workspace-utah/src/main/resources/services/metadata.xml
  deegree-workspaces/deegree-workspace-utah/src/main/resources/services/wfs110_metadata.xml
  deegree-workspaces/deegree-workspace-utah/src/main/resources/services/wfs_metadata.xml
  deegree-workspaces/deegree-workspace-utah/src/main/resources/services/wms_metadata.xml
  deegree-workspaces/deegree-workspace-utah/src/main/resources/services/wmts_metadata.xml
  deegree-workspaces/deegree-workspace-wcts/src/main/resources/services/metadata.xml
  deegree-workspaces/deegree-workspace-wps/src/main/resources/services/metadata.xml
Labels: enhancement, workspace, tests

#1501 3.4 main release pipeline
  Jenkinsfile
Labels: CI and build

#1512 Enabled release build for 3.4
  Jenkinsfile
Labels: enhancement

#1513 3.5 main release pipeline
  Jenkinsfile
Labels: CI and build

#1514 Fixed default param values and added -DdeployAtEnd=true
  Jenkinsfile
Labels: CI and build

#1519 Fixed build step for quality checks by using the warnings ng jenkins plugin
  Jenkinsfile
Labels: CI and build

#1525 Upgrade of maven surefire and failsafe plugins to v3.1.0
  pom.xml
Labels: CI and build
