Repository deegree/deegree3, pull requests merged in 2023-08, with the labels that each got.

#1555 GetFeature request with BBOX filter returns error in blob mode
  deegree-datastores/deegree-featurestores/deegree-featurestore-sql/src/main/java/org/deegree/feature/persistence/sql/SQLFeatureStore.java
Labels: bug

#1533 Upgrading maven plugins to latest versions
  deegree-tools/deegree-tools-gml/pom.xml
  pom.xml
  src/site/site.xml
Labels: enhancement, CI and build

#1438 Use official jgridshift version with patch
  deegree-core/deegree-core-cs/pom.xml
  deegree-core/deegree-core-cs/src/main/java/org/deegree/cs/transformations/ntv2/NTv2Transformation.java
  pom.xml
Labels: dependencies

#1563 Upgrade of maven plugins for surefire, failsafe, war, release to latest bugfix version
  deegree-workspaces/pom.xml
  pom.xml
Labels: enhancement, dependencies, CI and build

#1565 Upgrade of Primefaces from 12.0 to 13.0
  deegree-services/deegree-webservices/pom.xml
Labels: enhancement, console, dependencies

#1547 Fix invalid WMS metadata configuration for Utah workspace
  deegree-workspaces/deegree-workspace-utah/src/main/resources/services/wms_metadata.xml
Labels: bug, console, workspace

#1489 Improved tests for GMLGeometryValidator handling left- and right-handed CRS
  deegree-core/deegree-core-base/src/test/java/org/deegree/geometry/gml/validation/GmlGeometryValidatorTest.java
  deegree-core/deegree-core-base/src/test/resources/org/deegree/gml/misc/geometry/invalid/LeftHanded_exterior_anticlockwise_interior_anticlockwise.gml
  deegree-core/deegree-core-base/src/test/resources/org/deegree/gml/misc/geometry/invalid/LeftHanded_exterior_anticlockwise_interior_clockwise.gml
  deegree-core/deegree-core-base/src/test/resources/org/deegree/gml/misc/geometry/invalid/LeftHanded_exterior_clockwise_interior_anticlockwise.gml
  deegree-core/deegree-core-base/src/test/resources/org/deegree/gml/misc/geometry/invalid/LeftHanded_exterior_clockwise_interior_clockwise.gml
  deegree-core/deegree-core-base/src/test/resources/org/deegree/gml/misc/geometry/invalid/RightHanded_exterior_anticlockwise_interior_anticlockwise.gml
  deegree-core/deegree-core-base/src/test/resources/org/deegree/gml/misc/geometry/invalid/RightHanded_exterior_anticlockwise_interior_clockwise.gml
  deegree-core/deegree-core-base/src/test/resources/org/deegree/gml/misc/geometry/invalid/RightHanded_exterior_clockwise_interior_anticlockwise.gml
  deegree-core/deegree-core-base/src/test/resources/org/deegree/gml/misc/geometry/invalid/RightHanded_exterior_clockwise_interior_clockwise.gml
Labels: enhancement, tests
