Repository deegree/deegree3, pull requests merged in 2024-06, with the labels that each got.

#1696 Change SLF4J implementation of log4j2 to be compatible to SLF4J 2.x
  deegree-services/deegree-webservices/pom.xml
  deegree-tests/deegree-compliance-tests/pom.xml
  deegree-tests/deegree-integration-tests/pom.xml
  deegree-tests/deegree-wms-remoteows-tests/pom.xml
  deegree-tests/deegree-wms-similarity-tests/pom.xml
  deegree-tests/deegree-wmts-tests/pom.xml
  deegree-tests/deegree-workspace-tests/pom.xml
  deegree-tools/deegree-tools-3d/pom.xml
  deegree-tools/deegree-tools-base/pom.xml
  pom.xml
Labels: bug, core

#1695 Fix deegree admin console: scan beans, implement serializable
  deegree-client/deegree-jsf-core/src/main/java/org/deegree/client/core/debug/DebugPhaseListener.java
  deegree-client/deegree-jsf-core/src/main/resources/META-INF/beans.xml
  deegree-services/deegree-webservices/src/main/java/org/deegree/console/connection/remoteows/CreateRemoteOwsBean.java
  deegree-services/deegree-webservices/src/main/java/org/deegree/console/connection/sql/ConnectionTester.java
  deegree-services/deegree-webservices/src/main/java/org/deegree/console/connection/sql/CreateSqlConnectionBean.java
  deegree-services/deegree-webservices/src/main/java/org/deegree/console/datastore/coverage/CreateCoverageBean.java
  deegree-services/deegree-webservices/src/main/java/org/deegree/console/datastore/feature/CreateFeatureStoreBean.java
  deegree-services/deegree-webservices/src/main/java/org/deegree/console/datastore/feature/MappingWizardSQL.java
  deegree-services/deegree-webservices/src/main/java/org/deegree/console/datastore/metadata/CreateMetadataStoreBean.java
  deegree-services/deegree-webservices/src/main/java/org/deegree/console/datastore/tile/CreateTileStoreBean.java
  deegree-services/deegree-webservices/src/main/java/org/deegree/console/layer/layer/CreateLayerBean.java
  deegree-services/deegree-webservices/src/main/java/org/deegree/console/layer/style/CreateStyleBean.java
  deegree-services/deegree-webservices/src/main/java/org/deegree/console/layer/theme/CreateThemeBean.java
  deegree-services/deegree-webservices/src/main/java/org/deegree/console/process/CreateProcessBean.java
  deegree-services/deegree-webservices/src/main/java/org/deegree/console/proxy/ProxyBean.java
  deegree-services/deegree-webservices/src/main/java/org/deegree/console/webservices/CreateServiceBean.java
  deegree-services/deegree-webservices/src/main/java/org/deegree/console/webservices/wps/ProcessExecutionsBean.java
  deegree-services/deegree-webservices/src/main/java/org/deegree/console/webservices/wps/WPSBean.java
  deegree-services/deegree-webservices/src/main/java/org/deegree/console/workspace/CreateWorkspaceBean.java
  deegree-services/deegree-webservices/src/main/resources/META-INF/beans.xml
Labels: console

#1691 Replace String.replaceAll and String.replaceFirst with precompiled java.util.regex.Pattern to speed up String replacements
  deegree-core/deegree-core-base/src/test/java/org/deegree/gml/feature/GMLFeatureWriterTest.java
  deegree-core/deegree-core-commons/src/main/java/org/deegree/commons/utils/StringUtils.java
  deegree-core/deegree-core-commons/src/main/java/org/deegree/commons/xml/schema/RedirectingEntityResolver.java
  deegree-core/deegree-core-commons/src/test/java/org/deegree/commons/utils/StringToolsTest.java
  deegree-core/deegree-core-coverage/src/main/java/org/deegree/coverage/rangeset/Interval.java
  deegree-core/deegree-core-coverage/src/main/java/org/deegree/coverage/raster/cache/CacheRasterReader.java
  deegree-core/deegree-core-coverage/src/main/java/org/deegree/coverage/raster/data/info/BandType.java
  deegree-core/deegree-core-coverage/src/main/java/org/deegree/coverage/raster/interpolation/InterpolationType.java
  deegree-core/deegree-core-cs/src/main/java/org/deegree/cs/configuration/wkt/WKTParser.java
  deegree-core/deegree-core-sqldialect/deegree-sqldialect-commons/src/main/java/org/deegree/sqldialect/filter/AbstractWhereBuilder.java
  deegree-core/deegree-core-style/src/main/java/org/deegree/style/styling/wkn/TrueTypeFontLoader.java
  deegree-datastores/deegree-mdstores/deegree-mdstore-iso/src/main/java/org/deegree/metadata/iso/persistence/inspectors/IdUtils.java
  deegree-datastores/deegree-mdstores/deegree-mdstore-iso/src/main/java/org/deegree/metadata/iso/persistence/sql/AbstractSqlHelper.java
  deegree-services/deegree-services-commons/src/main/java/org/deegree/services/metadata/provider/DefaultOwsMetadataProviderBuilder.java
  deegree-services/deegree-services-wcs/src/main/java/org/deegree/services/wcs/capabilities/Capabilities100XMLAdapter.java
  deegree-services/deegree-services-wcs/src/main/java/org/deegree/services/wcs/describecoverage/CoverageDescription100XMLAdapter.java
  deegree-services/deegree-services-wfs/src/main/java/org/deegree/services/wfs/WebFeatureService.java
  deegree-services/deegree-services-wms/src/main/java/org/deegree/services/wms/controller/capabilities/theme/DatasetMetadataFactory.java
  deegree-tools/deegree-tools-3d/src/main/java/org/deegree/tools/rendering/manager/buildings/BuildingManager.java
  deegree-tools/deegree-tools-gml/src/main/java/org/deegree/tools/featurestoresql/config/FeatureStoreConfigWriter.java
Labels: enhancement, core

#1697 Fixed code formatting
  deegree-services/deegree-webservices/src/main/java/org/deegree/console/datastore/feature/MappingWizardSQL.java
Labels: easy

#1417 Register True-Type fonts at workspace startup
  deegree-core/deegree-core-commons/src/main/java/org/deegree/commons/font/WorkspaceFonts.java
  deegree-core/deegree-core-commons/src/main/resources/META-INF/services/org.deegree.workspace.Initializable
  deegree-core/deegree-core-commons/src/test/java/org/deegree/commons/config/WorkspaceFontTest.java
  deegree-core/deegree-core-commons/src/test/resources/org/deegree/commons/fontworkspace/fonts/DummyFont.LICENSE.txt
  deegree-core/deegree-core-commons/src/test/resources/org/deegree/commons/fontworkspace/fonts/DummyFont.ttf
  deegree-services/deegree-webservices-handbook/src/main/asciidoc/appendix.adoc
  deegree-services/deegree-webservices-handbook/src/main/asciidoc/basics.adoc
Labels: enhancement, TMC discussion, WMS, workspace

#1703 Several bug fixes for the admin console (Faces 4.0)
  deegree-services/deegree-webservices/src/main/java/org/deegree/console/Config.java
  deegree-services/deegree-webservices/src/main/java/org/deegree/console/connection/sql/ConnectionTester.java
  deegree-services/deegree-webservices/src/main/java/org/deegree/console/connection/sql/JdbcBean.java
  deegree-services/deegree-webservices/src/main/java/org/deegree/console/datastore/feature/FeatureStoreConfig.java
  deegree-services/deegree-webservices/src/main/java/org/deegree/console/datastore/feature/MappingWizardSQL.java
  deegree-services/deegree-webservices/src/main/java/org/deegree/console/datastore/metadata/MetadataStoreConfig.java
  deegree-services/deegree-webservices/src/main/java/org/deegree/console/generic/Connection.java
  deegree-services/deegree-webservices/src/main/java/org/deegree/console/generic/XmlEditorBean.java
  deegree-services/deegree-webservices/src/main/java/org/deegree/console/moduleinfo/ModulesBean.java
  deegree-services/deegree-webservices/src/main/java/org/deegree/console/workspace/WorkspaceBean.java
  deegree-services/deegree-webservices/src/main/webapp/console/generic/sql.xhtml
Labels: bug, console

#1708 Changing format of password stored in console.pw to UNIX crypt extended format
  deegree-services/deegree-webservices/pom.xml
  deegree-services/deegree-webservices/src/main/java/org/deegree/console/security/LogBean.java
  deegree-services/deegree-webservices/src/main/java/org/deegree/console/security/PasswordFile.java
  deegree-services/deegree-webservices/src/main/java/org/deegree/console/security/SaltedPassword.java
  deegree-services/deegree-webservices/src/test/java/org/deegree/console/security/PasswordFileTest.java
  deegree-services/deegree-webservices/src/test/java/org/deegree/console/security/SaltedPasswordTest.java
Labels: enhancement, breaking

#1707 Upgrade Jenkinsfile to temurin 17 / Java 17
  Jenkinsfile
Labels: dependencies, CI and build

#1709 Fix some faces errors in admin console
  deegree-services/deegree-webservices/src/main/java/org/deegree/console/generic/XmlEditorBean.java
  deegree-services/deegree-webservices/src/main/webapp/WEB-INF/web.xml
  deegree-services/deegree-webservices/src/main/webapp/layout.xhtml
Labels: bug, console

#1711 Removed the unmaintained and unused deegree.module.status property
  deegree-client/deegree-jsf-core/pom.xml
  deegree-core/deegree-connectionprovider-datasource/pom.xml
  deegree-core/deegree-core-3d/pom.xml
  deegree-core/deegree-core-annotations/pom.xml
  deegree-core/deegree-core-base/pom.xml
  deegree-core/deegree-core-commons/pom.xml
  deegree-core/deegree-core-coverage/pom.xml
  deegree-core/deegree-core-cs/pom.xml
  deegree-core/deegree-core-db/pom.xml
  deegree-core/deegree-core-featureinfo/pom.xml
  deegree-core/deegree-core-filterfunctions/pom.xml
  deegree-core/deegree-core-gdal/pom.xml
  deegree-core/deegree-core-geometry/pom.xml
  deegree-core/deegree-core-metadata/pom.xml
  deegree-core/deegree-core-protocol/deegree-protocol-commons/pom.xml
  deegree-core/deegree-core-protocol/deegree-protocol-wfs/pom.xml
  deegree-core/deegree-core-remoteows/deegree-remoteows-commons/pom.xml
  deegree-core/deegree-core-remoteows/deegree-remoteows-wms/pom.xml
  deegree-core/deegree-core-remoteows/deegree-remoteows-wmts/pom.xml
  deegree-core/deegree-core-rendering-2d/pom.xml
  deegree-core/deegree-core-sqldialect/deegree-sqldialect-commons/pom.xml
  deegree-core/deegree-core-sqldialect/deegree-sqldialect-mssql/pom.xml
  deegree-core/deegree-core-theme/pom.xml
  deegree-core/deegree-core-tile/pom.xml
  deegree-core/deegree-core-workspace/pom.xml
  deegree-datastores/deegree-featurestores/deegree-featurestore-commons/pom.xml
  deegree-datastores/deegree-featurestores/deegree-featurestore-shape/pom.xml
  deegree-datastores/deegree-featurestores/deegree-featurestore-simplesql/pom.xml
  deegree-datastores/deegree-featurestores/deegree-featurestore-sql/pom.xml
  deegree-datastores/deegree-mdstores/deegree-mdstore-commons/pom.xml
  deegree-datastores/deegree-tilestores/deegree-tilestore-filesystem/pom.xml
  deegree-datastores/deegree-tilestores/deegree-tilestore-geotiff/pom.xml
  deegree-layers/deegree-layers-coverage/pom.xml
  deegree-layers/deegree-layers-feature/pom.xml
  deegree-layers/deegree-layers-gdal/pom.xml
  deegree-services/deegree-services-commons/pom.xml
  deegree-services/deegree-services-config/pom.xml
  deegree-services/deegree-services-csw/pom.xml
  deegree-services/deegree-services-wcs/pom.xml
  deegree-services/deegree-services-wfs/pom.xml
  deegree-services/deegree-services-wms/pom.xml
  deegree-services/deegree-services-wmts/pom.xml
  deegree-services/deegree-services-wps/pom.xml
  deegree-services/deegree-services-wpvs/pom.xml
  deegree-services/deegree-webservices/pom.xml
  deegree-themes/deegree-themes-remotewms/pom.xml
  deegree-workspaces/deegree-workspace-geosciml/pom.xml
  deegree-workspaces/deegree-workspace-utah/pom.xml
  deegree-workspaces/deegree-workspace-wcts/pom.xml
Labels: enhancement, CI and build

#1710 Upgrading Spring Boot to v3.3 with Spring Framework 6.1 and Spring Batch 5.1 with JDK 17
  deegree-tools/deegree-tools-gml/pom.xml
  deegree-tools/deegree-tools-gml/src/main/java/org/deegree/tools/featurestoresql/GmlToolsApp.java
  deegree-tools/deegree-tools-gml/src/main/java/org/deegree/tools/featurestoresql/JobRepositoryConfiguration.java
  deegree-tools/deegree-tools-gml/src/main/java/org/deegree/tools/featurestoresql/SubcommandApp.java
  deegree-tools/deegree-tools-gml/src/main/java/org/deegree/tools/featurestoresql/config/FeatureStoreConfigWriter.java
  deegree-tools/deegree-tools-gml/src/main/java/org/deegree/tools/featurestoresql/config/SqlFeatureStoreConfigCreatorApp.java
  deegree-tools/deegree-tools-gml/src/main/java/org/deegree/tools/featurestoresql/config/SqlFeatureStoreConfigCreatorConfiguration.java
  deegree-tools/deegree-tools-gml/src/main/java/org/deegree/tools/featurestoresql/loader/FeatureStoreWriter.java
  deegree-tools/deegree-tools-gml/src/main/java/org/deegree/tools/featurestoresql/loader/GmlLoaderApp.java
  deegree-tools/deegree-tools-gml/src/main/java/org/deegree/tools/featurestoresql/loader/NullWriter.java
  deegree-tools/deegree-tools-gml/src/main/java/org/deegree/tools/featurestoresql/loader/ReportWriter.java
  deegree-tools/deegree-tools-gml/src/test/java/org/deegree/tools/featurestoresql/GmlToolsAppTest.java
  deegree-tools/deegree-tools-gml/src/test/java/org/deegree/tools/featurestoresql/config/SqlFeatureStoreConfigCreatorAppTest.java
  deegree-tools/deegree-tools-gml/src/test/java/org/deegree/tools/featurestoresql/loader/FeatureReferencesParserTest.java
  deegree-tools/deegree-tools-gml/src/test/java/org/deegree/tools/featurestoresql/loader/FeatureReferencesParserTestConfig.java
  deegree-tools/deegree-tools-gml/src/test/java/org/deegree/tools/featurestoresql/loader/GmlLoaderAppTest.java
  pom.xml
Labels: dependencies

#1713 Fixed workspace download in admin console
  deegree-client/deegree-jsf-core/src/main/java/org/deegree/client/core/utils/ActionParams.java
Labels: bug, console

#1716 Upgraded primefaces to version 13.0.10/11
  deegree-services/deegree-webservices/pom.xml
Labels: CVE, dependencies
