Repository deegree/deegree3, pull requests merged in 2024-01, with the labels that each got.

#1619 Fix buffer issue when response buffering is active and a short results
  deegree-services/deegree-services-commons/src/main/java/org/deegree/services/controller/utils/HttpResponseBuffer.java
  deegree-services/deegree-services-commons/src/test/java/org/deegree/services/controller/utils/HttpResponseBufferTest.java
Labels: bug, WFS, core

#1632 Fix regression with SVG that would be rendered smaller than one pixel
  deegree-core/deegree-core-rendering-2d/src/main/java/org/deegree/rendering/r2d/SvgRenderer.java
  deegree-core/deegree-core-rendering-2d/src/test/java/org/deegree/rendering/r2d/SvgRendererTests.java
Labels: bug, WMS

#1623 Add GeoJSON as GetFeatureInfoFormat (deegree 3.6)
  deegree-core/deegree-core-base/src/main/java/org/deegree/geojson/GeoJsonWriter.java
  deegree-core/deegree-core-base/src/test/java/org/deegree/geojson/GeoJsonFeatureWriterTest.java
  deegree-core/deegree-core-featureinfo/src/main/java/org/deegree/featureinfo/FeatureInfoContext.java
  deegree-core/deegree-core-featureinfo/src/main/java/org/deegree/featureinfo/FeatureInfoManager.java
  deegree-core/deegree-core-featureinfo/src/main/java/org/deegree/featureinfo/FeatureInfoParams.java
  deegree-core/deegree-core-featureinfo/src/main/java/org/deegree/featureinfo/serializing/GeoJsonFeatureInfoSerializer.java
  deegree-core/deegree-core-featureinfo/src/test/java/org/deegree/featureinfo/serializing/GeoJsonFeatureInfoSerializerTest.java
  deegree-core/deegree-core-featureinfo/src/test/java/org/deegree/featureinfo/serializing/TemplateFeatureInfoSerializerTest.java
  deegree-core/deegree-core-featureinfo/src/test/resources/org/deegree/featureinfo/serializing/featurecollection.gml
  deegree-core/deegree-core-protocol/deegree-protocol-wms/src/main/java/org/deegree/protocol/wms/ops/GetFeatureInfo.java
  deegree-services/deegree-services-commons/src/main/java/org/deegree/services/controller/utils/StandardFeatureInfoContext.java
  deegree-services/deegree-services-wms/src/main/java/org/deegree/services/wms/controller/WMSController.java
  deegree-services/deegree-services-wms/src/main/resources/META-INF/schemas/services/wms/wms_configuration.xsd
  deegree-services/deegree-services-wmts/src/main/java/org/deegree/services/wmts/controller/FeatureInfoFetcher.java
  deegree-services/deegree-webservices-handbook/src/main/asciidoc/webservices.adoc
Labels: feature, WMS
