Repository deegree/deegree3, pull requests merged in 2024-04, with the labels that each got.

#1672 Upgrade json path library to latest version (3.5)
  deegree-core/deegree-core-commons/pom.xml
  pom.xml
Labels: dependencies

#1670 Upgrade json path library to latest version
  deegree-core/deegree-core-commons/pom.xml
  pom.xml
Labels: dependencies

#1669 Upgrade dependencies of Apache commons pool, and dbcp2 to latest version
  deegree-core/deegree-connectionprovider-datasource/src/main/resources/META-INF/schemas/connectionprovider/datasource/example_dbcp_mssql.xml
  deegree-core/deegree-connectionprovider-datasource/src/main/resources/META-INF/schemas/connectionprovider/datasource/example_dbcp_oracle.xml
  deegree-core/deegree-connectionprovider-datasource/src/main/resources/META-INF/schemas/connectionprovider/datasource/example_dbcp_postgres.xml
  pom.xml
Labels: enhancement, dependencies

#1674 Enhanced GmlTool to support multiple namespaces with same prefix in one application schema (3.5)
  deegree-core/deegree-core-commons/src/main/java/org/deegree/commons/xml/schema/XMLSchemaInfoSet.java
Labels: bug, tools

#1668 Fix issue where CustomConverter is ignored in table-driven feature mapping mode and provide exemplary implementations [3.6]
  deegree-datastores/deegree-featurestores/deegree-featurestore-sql/pom.xml
  deegree-datastores/deegree-featurestores/deegree-featurestore-sql/src/main/java/org/deegree/feature/persistence/sql/config/MappedSchemaBuilderTable.java
  deegree-datastores/deegree-featurestores/deegree-featurestore-sql/src/main/java/org/deegree/feature/persistence/sql/converter/AbstractStringPrimitiveConverter.java
  deegree-datastores/deegree-featurestores/deegree-featurestore-sql/src/main/java/org/deegree/feature/persistence/sql/converter/BinaryBase64PrimitiveConverter.java
  deegree-datastores/deegree-featurestores/deegree-featurestore-sql/src/main/java/org/deegree/feature/persistence/sql/converter/BinaryDataUrlPrimitiveConverter.java
  deegree-datastores/deegree-featurestores/deegree-featurestore-sql/src/main/java/org/deegree/feature/persistence/sql/converter/CharacterPrimitiveConverter.java
  deegree-services/deegree-webservices-handbook/src/main/asciidoc/appendix.adoc
  deegree-services/deegree-webservices-handbook/src/main/asciidoc/featurestores.adoc
Labels: bug, enhancement, core

#1665 Fix issue where CustomConverter is ignored in table-driven feature mapping mode and provide exemplary implementations [3.5]
  deegree-datastores/deegree-featurestores/deegree-featurestore-sql/pom.xml
  deegree-datastores/deegree-featurestores/deegree-featurestore-sql/src/main/java/org/deegree/feature/persistence/sql/config/MappedSchemaBuilderTable.java
  deegree-datastores/deegree-featurestores/deegree-featurestore-sql/src/main/java/org/deegree/feature/persistence/sql/converter/AbstractStringPrimitiveConverter.java
  deegree-datastores/deegree-featurestores/deegree-featurestore-sql/src/main/java/org/deegree/feature/persistence/sql/converter/BinaryBase64PrimitiveConverter.java
  deegree-datastores/deegree-featurestores/deegree-featurestore-sql/src/main/java/org/deegree/feature/persistence/sql/converter/BinaryDataUrlPrimitiveConverter.java
  deegree-datastores/deegree-featurestores/deegree-featurestore-sql/src/main/java/org/deegree/feature/persistence/sql/converter/CharacterPrimitiveConverter.java
  deegree-services/deegree-webservices-handbook/src/main/asciidoc/appendix.adoc
  deegree-services/deegree-webservices-handbook/src/main/asciidoc/featurestores.adoc
Labels: bug, enhancement, core

#1673 Fixed evaluation of reference data (3.6)
  deegree-datastores/deegree-featurestores/deegree-featurestore-sql/src/main/java/org/deegree/feature/persistence/sql/mapper/AppSchemaMapper.java
  deegree-datastores/deegree-featurestores/deegree-featurestore-sql/src/main/java/org/deegree/feature/persistence/sql/mapper/CycleAnalyser.java
  deegree-datastores/deegree-featurestores/deegree-featurestore-sql/src/main/java/org/deegree/feature/persistence/sql/mapper/GmlReferenceData.java
  deegree-datastores/deegree-featurestores/deegree-featurestore-sql/src/main/java/org/deegree/feature/persistence/sql/mapper/PathStep.java
  deegree-datastores/deegree-featurestores/deegree-featurestore-sql/src/main/java/org/deegree/feature/persistence/sql/mapper/ReferenceData.java
  deegree-datastores/deegree-featurestores/deegree-featurestore-sql/src/test/java/org/deegree/feature/persistence/sql/mapper/AppSchemaMapperTest.java
  deegree-datastores/deegree-featurestores/deegree-featurestore-sql/src/test/java/org/deegree/feature/persistence/sql/mapper/GmlReferenceDataTest.java
  deegree-datastores/deegree-featurestores/deegree-featurestore-sql/src/test/resources/org/deegree/feature/persistence/sql/mapper/data/Inspire-MineralResources.xml
Labels: bug, tools

#1667 Fixed evaluation of reference data (3.5)
  deegree-datastores/deegree-featurestores/deegree-featurestore-sql/src/main/java/org/deegree/feature/persistence/sql/mapper/AppSchemaMapper.java
  deegree-datastores/deegree-featurestores/deegree-featurestore-sql/src/main/java/org/deegree/feature/persistence/sql/mapper/CycleAnalyser.java
  deegree-datastores/deegree-featurestores/deegree-featurestore-sql/src/main/java/org/deegree/feature/persistence/sql/mapper/GmlReferenceData.java
  deegree-datastores/deegree-featurestores/deegree-featurestore-sql/src/main/java/org/deegree/feature/persistence/sql/mapper/PathStep.java
  deegree-datastores/deegree-featurestores/deegree-featurestore-sql/src/main/java/org/deegree/feature/persistence/sql/mapper/ReferenceData.java
  deegree-datastores/deegree-featurestores/deegree-featurestore-sql/src/test/java/org/deegree/feature/persistence/sql/mapper/AppSchemaMapperTest.java
  deegree-datastores/deegree-featurestores/deegree-featurestore-sql/src/test/java/org/deegree/feature/persistence/sql/mapper/GmlReferenceDataTest.java
  deegree-datastores/deegree-featurestores/deegree-featurestore-sql/src/test/resources/org/deegree/feature/persistence/sql/mapper/data/Inspire-MineralResources.xml
Labels: bug, tools

#1644 Added schema to table name to create the index
  deegree-datastores/deegree-featurestores/deegree-featurestore-sql/src/main/java/org/deegree/feature/persistence/sql/ddl/PostGISDDLCreator.java
Labels: enhancement, tools

#1629 Add support of srsName in StoredQueries
  deegree-services/deegree-services-wfs/src/main/java/org/deegree/services/wfs/query/QueryAnalyzer.java
  deegree-services/deegree-webservices-handbook/src/main/asciidoc/webservices.adoc
Labels: enhancement, WFS

#1680 Upgraded PostGIS JDBC driver to v2023.1.0 with support for Java 9+
  deegree-core/deegree-core-sqldialect/deegree-sqldialect-postgis/src/main/java/org/deegree/sqldialect/postgis/PostGISDialect.java
  deegree-services/deegree-services-wpvs/src/main/java/org/deegree/services/wpvs/io/db/PostgisBackend.java
  deegree-tools/deegree-tools-base/src/main/java/org/deegree/tools/coverage/gridifier/index/MultiLevelMemoryTileGridIndex.java
  deegree-tools/deegree-tools-base/src/main/java/org/deegree/tools/coverage/gridifier/index/PostGISRasterTileIndex.java
  pom.xml
Labels: enhancement, dependencies

#1677 Enhanced documention with examples how to configure different connection pool provider
  deegree-services/deegree-webservices-handbook/src/main/asciidoc/javamodules.adoc
  deegree-services/deegree-webservices-handbook/src/main/asciidoc/serverconnections.adoc
Labels: enhancement, documentation
