Repository deegree/deegree3, pull requests merged in 2024-03, with the labels that each got.

#1630 Enhance configurability of WFS output format for defaults and CSV
  deegree-services/deegree-services-wfs/src/main/java/org/deegree/services/wfs/WebFeatureService.java
  deegree-services/deegree-services-wfs/src/main/java/org/deegree/services/wfs/format/csv/CsvFeatureWriter.java
  deegree-services/deegree-services-wfs/src/main/java/org/deegree/services/wfs/format/csv/CsvFormat.java
  deegree-services/deegree-services-wfs/src/main/java/org/deegree/services/wfs/format/csv/CsvFormatConfig.java
  deegree-services/deegree-services-wfs/src/main/java/org/deegree/services/wfs/format/csv/request/CsvGetFeatureHandler.java
  deegree-services/deegree-services-wfs/src/main/resources/META-INF/schemas/services/wfs/wfs_configuration.xsd
  deegree-services/deegree-services-wfs/src/test/java/org/deegree/services/wfs/format/csv/CsvFeatureWriterTest.java
  deegree-services/deegree-webservices-handbook/src/main/asciidoc/webservices.adoc
Labels: enhancement, ready, WFS, schema change

#1656 Upgraded dependencies to latest bugfix versions (3.6)
  deegree-services/deegree-webservices/pom.xml
  pom.xml
Labels: dependencies

#1655 Upgraded dependencies to latest bugfix versions (3.5)
  deegree-services/deegree-webservices/pom.xml
  pom.xml
Labels: dependencies

#1657 Upgraded dependencies to latest bugfix versions (3.4)
  deegree-services/deegree-webservices/pom.xml
  deegree-tools/deegree-tools-gml/pom.xml
  pom.xml
Labels: dependencies

#1661 Added support of patches in DefaultSurface.buildJTSGeometry() (3.5)
  deegree-core/deegree-core-geometry/src/main/java/org/deegree/geometry/standard/primitive/DefaultSurface.java
Labels: enhancement, WFS, core

#1658 Added support of patches in DefaultSurface.buildJTSGeometry() (3.6)
  deegree-core/deegree-core-geometry/src/main/java/org/deegree/geometry/standard/primitive/DefaultSurface.java
Labels: enhancement, WFS, core

#1651 Ensure mapping for inline features (deegree 3.5)
  deegree-datastores/deegree-featurestores/deegree-featurestore-sql/src/main/java/org/deegree/feature/persistence/sql/mapper/GmlReferenceData.java
  deegree-datastores/deegree-featurestores/deegree-featurestore-sql/src/test/java/org/deegree/feature/persistence/sql/mapper/GmlReferenceDataTest.java
  deegree-datastores/deegree-featurestores/deegree-featurestore-sql/src/test/resources/org/deegree/feature/persistence/sql/mapper/data/Inspire-Adress_withInlineFeature.xml
Labels: bug

#1650 Ensure mapping for inline features (deegree 3.6)
  deegree-datastores/deegree-featurestores/deegree-featurestore-sql/src/main/java/org/deegree/feature/persistence/sql/mapper/GmlReferenceData.java
  deegree-datastores/deegree-featurestores/deegree-featurestore-sql/src/test/java/org/deegree/feature/persistence/sql/mapper/GmlReferenceDataTest.java
  deegree-datastores/deegree-featurestores/deegree-featurestore-sql/src/test/resources/org/deegree/feature/persistence/sql/mapper/data/Inspire-Adress_withInlineFeature.xml
Labels: bug

#1663 Upgrade dependencies gson, commons-collections4 and maven plugins (3.5)
  pom.xml
Labels: dependencies

#1671 Upgrade dependencies gson, commons-collections4 and maven plugins (3.6)
  pom.xml
Labels: dependencies

#1664 Return false is geometry property does not exists (3.6)
  deegree-core/deegree-core-filterfunctions/src/main/java/org/deegree/filter/function/geometry/IsCurve.java
  deegree-core/deegree-core-filterfunctions/src/main/java/org/deegree/filter/function/geometry/IsPoint.java
  deegree-core/deegree-core-filterfunctions/src/main/java/org/deegree/filter/function/geometry/IsSurface.java
Labels: WFS
