Repository deegree/deegree3, pull requests merged in 2024-11, with the labels that each got.

#1755 Fix URL creation when header X-Forwarded-Port and X-Forwarded-Host with port are used (3.6)
  deegree-services/deegree-services-commons/src/api/java/org/deegree/services/controller/OGCFrontController.java
  deegree-services/deegree-services-commons/src/test/java/org/deegree/services/controller/OGCFrontControllerTest.java
Labels: bug, ready, core

#1756 Fix URL creation when header X-Forwarded-Port and X-Forwarded-Host with port are used (3.5)
  deegree-services/deegree-services-commons/src/api/java/org/deegree/services/controller/OGCFrontController.java
  deegree-services/deegree-services-commons/src/test/java/org/deegree/services/controller/OGCFrontControllerTest.java
Labels: bug, ready, core

#1736 Upgraded dependencies: jts, slf4j, extra-enforcer-rules, xmlunit-matchers
  deegree-client/deegree-jsf-core/pom.xml
  deegree-services/deegree-webservices/pom.xml
  pom.xml
Labels: dependencies

#1739 Upgraded to imageio-ext to latest version 1.4.12
  pom.xml
Labels: dependencies

#1737 Added property with add-opens, add-exports JVM arguments
  deegree-services/deegree-webservices/pom.xml
  deegree-tests/pom.xml
  pom.xml
Labels: enhancement, CI and build

#1761 Upgraded Primefaces to latest bugfix version 14.0.6 to resolve critical CVE (3.5)
  deegree-services/deegree-webservices/pom.xml
  pom.xml
Labels: ready, console, CVE, dependencies

#1762 Upgraded Primefaces and other dependencies to latest bugfix version (3.6)
  deegree-services/deegree-webservices/pom.xml
  pom.xml
Labels: dependencies

#1742 Upgraded Spring Boot to v3.3.5
  pom.xml
Labels: ready, dependencies

#1759 Fix missing JobBuilderFactory bean in GmlLoaderConfiguration
  deegree-tools/deegree-tools-gml/pom.xml
  deegree-tools/deegree-tools-gml/src/main/java/org/deegree/tools/featurestoresql/loader/GmlLoaderConfiguration.java
  deegree-tools/deegree-tools-gml/src/main/java/org/deegree/tools/featurestoresql/loader/ReportWriter.java
  deegree-tools/deegree-tools-gml/src/test/java/org/deegree/tools/featurestoresql/loader/GmlLoaderConfigurationTest.java
  deegree-tools/deegree-tools-gml/src/test/java/org/deegree/tools/featurestoresql/loader/ReportWriterTest.java
Labels: bug, tools, core
