Repository deegree/deegree3, pull requests merged in 2024-10, with the labels that each got.

#1749 Remove remote layer pointing to external URL from deegree-workspace-utah
  deegree-workspaces/deegree-workspace-utah/src/main/resources/datasources/remoteows/cascade_utah_geology_wms.xml
  deegree-workspaces/deegree-workspace-utah/src/main/resources/layers/layer_remotewms_utah_geology.xml
Labels: CI and build, workspace, tests

#1748 Upgraded jetty and soapUI maven plugins to latest bugfix version
  deegree-tests/deegree-integration-tests/pom.xml
  deegree-tests/pom.xml
  pom.xml
Labels: CI and build

#1745 Fixed value of nilReason (3.6)
  deegree-core/deegree-core-base/src/main/java/org/deegree/gml/feature/GMLFeatureWriter.java
Labels: bug

#1744 Fixed value of nilReason (3.5)
  deegree-core/deegree-core-base/src/main/java/org/deegree/gml/feature/GMLFeatureWriter.java
Labels: bug
