Repository deegree/deegree3, pull requests merged in 2024-07, with the labels that each got.

#1719 Fixed typo in maven property axiom.version
  pom.xml
Labels: CI and build

#1717 Upgraded maven plugins to latest version
  pom.xml
Labels: enhancement, CI and build

#1715 Remove links to HTTP and replace them with HTTPS
  pom.xml
  src/site/site.xml
Labels: enhancement, easy

#1712 Adjust the information displayed in the service metadata example of deegree
  deegree-services/deegree-services-commons/src/main/resources/META-INF/schemas/services/metadata/example.xml
Labels: enhancement, ready, easy

#1721 Write schemaLocation with https in WMS 1.1.3 capabilities (3.5)
  deegree-services/deegree-services-wms/src/main/java/org/deegree/services/wms/controller/capabilities/Capabilities130XMLAdapter.java
Labels: WMS

#1722 Write schemaLocation with https in WMS 1.1.3 capabilities (3.6)
  deegree-services/deegree-services-wms/src/main/java/org/deegree/services/wms/controller/capabilities/Capabilities130XMLAdapter.java
Labels: WMS

#1720 Upgraded dependencies to fit with Spring Boot 3.3.0
  pom.xml
Labels: dependencies
