Repository deegree/deegree3, pull requests merged in 2025-01, with the labels that each got.

#1765 Improvements for writing GeoJson for GML with nested geometries
  deegree-core/deegree-core-base/src/main/java/org/deegree/geojson/GeoJsonWriter.java
  deegree-core/deegree-core-base/src/test/java/org/deegree/geojson/GeoJsonFeatureWriterTest.java
  deegree-core/deegree-core-base/src/test/resources/org/deegree/geojson/govserv.xml
  deegree-core/deegree-core-base/src/test/resources/org/deegree/geojson/govserv_single-geom.xml
Labels: enhancement, WMS

#1775 Upgraded dependencies to latest bugfix versions
  deegree-core/deegree-core-sqldialect/deegree-sqldialect-postgis/src/main/java/org/deegree/sqldialect/postgis/PostGISDialect.java
  deegree-services/deegree-services-wpvs/src/main/java/org/deegree/services/wpvs/io/db/PostgisBackend.java
  deegree-services/deegree-webservices/pom.xml
  deegree-tools/deegree-tools-base/src/main/java/org/deegree/tools/coverage/gridifier/index/MultiLevelMemoryTileGridIndex.java
  deegree-tools/deegree-tools-base/src/main/java/org/deegree/tools/coverage/gridifier/index/PostGISRasterTileIndex.java
  pom.xml
Labels: dependencies

#1773 Fix external URL of soapwms schema
  deegree-services/deegree-services-wms/src/main/java/org/deegree/services/wms/controller/capabilities/Wms130SoapExtendedCapabilitesWriter.java
Labels: bug, WMS
