Repository deegree/deegree3, pull requests merged in 2025-09, with the labels that each got.

#1859 Fix SOAP WMS namespace (3.6)
  deegree-documentation/src/main/asciidoc/webservices.adoc
  deegree-services/deegree-services-wms/src/main/java/org/deegree/services/wms/controller/capabilities/Wms130SoapExtendedCapabilitesWriter.java
  deegree-services/deegree-services-wms/src/test/resources/org/deegree/services/wms/controller/capabilities/soapwms.xsd
Labels: bug, WMS

#1857 Upgraded maven dependencies and plugins to latest version
  deegree-services/deegree-webservices/pom.xml
  deegree-tools/deegree-tools-gml/pom.xml
  pom.xml
Labels: dependencies

#1867 Updated security policy
  SECURITY.md
Labels: website, documentation
