Repository deegree/deegree3, pull requests merged in 2025-07, with the labels that each got.

#1839 Migrate to Apache Commons Lang 3
  deegree-services/deegree-services-wfs/pom.xml
  deegree-services/deegree-services-wfs/src/main/java/org/deegree/services/wfs/WebFeatureService.java
  deegree-services/deegree-services-wfs/src/main/java/org/deegree/services/wfs/format/gml/GmlFormat.java
  pom.xml
Labels: CVE, dependencies

#1814 Fixed non-transparant WMS output for remote WMS and GDAL layers
  deegree-core/deegree-core-rendering-2d/src/main/java/org/deegree/rendering/r2d/context/ImageRenderContext.java
  deegree-core/deegree-core-style/src/main/java/org/deegree/style/utils/ImageUtils.java
Labels: bug, TMC discussion, under review, WMS

#1841 Fixes missing nil property (3.5)
  deegree-datastores/deegree-featurestores/deegree-featurestore-sql/src/main/java/org/deegree/feature/persistence/sql/rules/FeatureBuilderRelational.java
Labels: bug

#1842 Fix ConcurrentModifiationException (3.6)
  deegree-layers/deegree-layers-remotewms/src/main/java/org/deegree/layer/persistence/remotewms/RemoteWmsLayerBuilder.java
Labels: bug
